### ISSUE TITLE
Queries fail when using assume role auth method in a region with STS disabled

### ISSUE THREAD

**Issue by cbruno10** [turbot/steampipe-plugin-aws#1510] opened 2022-12-19 21:36 UTC
**Describe the bug**
When a region has its STS regional endpoint disabled, that region is included in the `regions` config arg, and the auth method for the AWS connection is assuming a role, the API will throw an error like:
```
Error: operation error EC2: DescribeInstances, failed to sign request: failed to retrieve credentials: failed to refresh cached credentials, operation error STS: AssumeRole, https response error StatusCode: 403, RequestID: a3556be4-6ace-479e-acd8-db5a74762c7c, RegionDisabledException: STS is not activated in this region for account:123456789012. Your account administrator can activate STS in this region using the IAM Console. (SQLSTATE HV000)
```

The above error is from running `select * from aws_ec2_instance;`.

**Steampipe version (`steampipe -v`)**
v0.18.0

**Plugin version (`steampipe plugin list`)**
v0.88.0

**To reproduce**
Create a connection in `aws.spc` with `regions` set to a region where the [STS regional endpoint is disabled](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_enable-regions.html#sts-regions-activate-deactivate), e.g., `regions = ["us-east-2"]` (assuming STS is disabled in us-east-2) and it uses [assume role creds](https://hub.steampipe.io/plugins/turbot/aws#assumerole-credentials-no-mfa).

Then run a query for a regional table, e.g., `select * from aws_ec2_instance;`.

**Expected behavior**
The plugin should fallback to the global STS endpoint if possible.

**Additional context**

**Comment by cbruno10** [comment] 2022-12-19 21:37
Notes from some testing:
- The error is not thrown by the SDK/API when creating the session or service client, but only when making an API call, e.g., EC2 `DescribeInstances`.
- In the CLI, AWS recommends setting the region to `aws-global` to force use of a global endpoint. Not sure if this works in the SDK though, or if it works with how we handle regions today. More info at https://docs.aws.amazon.com/sdkref/latest/guide/feature-sts-regionalized-endpoints.html.

**Comment by captainfalcon23** [comment] 2023-01-12 01:33
I am having this issue also. I tried adding "RegionDisabledException" to "ignore_error_codes" in aws.spc but still facing the issue.

**Comment by captainfalcon23** [comment] 2023-06-25 00:05
I believe this is resolved/duplicate of https://github.com/turbot/steampipe-plugin-aws/issues/1569. @e-gineer , I think this can be closed.

**Comment by misraved** [comment] 2023-06-26 05:22
Thanks @captainfalcon23 for following up on this issue 👍.

**Closed by misraved** 2023-06-26 05:22 UTC
Labels: bug
