### ISSUE TITLE
Queries getting hanged with new version. 

### ISSUE THREAD

**Issue by ManojDhanorkar** [turbot/steampipe-plugin-aws#2056] opened 2024-01-18 12:44 UTC
We have several queries for AWS. They were just running fine till 4 to 5 days back.  However suddenly they have started hanging  and it just does not return anything. 

The change that I noticed is version change.

Working:
Steampipe v0.21.3
Installed plugin: aws@latest v0.127.0

Not working:
steampipe -v
Steampipe v0.21.3
Installed plugin: aws@latest v0.128.0

Appreciate if you can take this on priority.

**Comment by ManojDhanorkar** [comment] 2024-01-19 08:49
In database logs file i see below error -------------

2024-01-19 08:41:55.916 UTC [WARN]  steampipe [83c5]: Error waiting for notification: read tcp 127.0.0.1:53164->127.0.0.1:9193: use of closed network connection
2024-01-19 08:46:04.098 UTC [WARN]  steampipe [ad3c]: Error waiting for notification: read tcp 127.0.0.1:53946->127.0.0.1:9193: use of closed network connection
2024-01-19 08:46:14.476 UTC [WARN]  steampipe [5be2]: Error waiting for notification: read tcp 127.0.0.1:51554->127.0.0.1:9193: use of closed network connection

**Comment by ManojDhanorkar** [comment] 2024-01-19 08:50
2024-01-19 08:46:04.097 UTC [WARN]  PluginManager Get failed for hub.steampipe.io/plugins/turbot/aws@latest: plugin manager is shutting down (0xc0007d8f80)

**Comment by ManojDhanorkar** [comment] 2024-01-19 08:50
somehow the plugin manager is shutting down.

**Comment by ManojDhanorkar** [comment] 2024-01-19 08:52
database logs-------------
2024-01-19 08:38:37.342 UTC [17869] LOG:  starting PostgreSQL 14.2 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 4.8.4-2ubuntu1~14.04.4) 4.8.4, 64-bit
2024-01-19 08:38:37.343 UTC [17869] LOG:  listening on IPv6 address "::1", port 9193
2024-01-19 08:38:37.343 UTC [17869] LOG:  listening on IPv4 address "127.0.0.1", port 9193
2024-01-19 08:38:37.346 UTC [17869] LOG:  listening on Unix socket "/tmp/.s.PGSQL.9193"
2024-01-19 08:38:37.357 UTC [17871] LOG:  database system was shut down at 2024-01-19 08:38:36 UTC
2024-01-19 08:38:37.366 UTC [17869] LOG:  database system is ready to accept connections
2024-01-19 08:38:37.487 UTC [17878] LOG:  connection received: host=127.0.0.1 port=39356
2024-01-19 08:38:37.488 UTC [17878] LOG:  connection authorized: user=root database=postgres application_name=steampipe_service_e6fe
2024-01-19 08:38:37.495 UTC [17878] LOG:  disconnection: session time: 0:00:00.007 user=root database=postgres host=127.0.0.1 port=39356
2024-01-19 08:38:37.498 UTC [17879] LOG:  connection received: host=127.0.0.1 port=39368
2024-01-19 08:38:37.503 UTC [17879] LOG:  connection authorized: user=root database=postgres application_name=steampipe_service_e6fe SSL enabled (protocol=TLSv1.2, cipher=ECDHE-RSA-AES256-GCM-SHA384, bits=256)
2024-01-19 08:38:37.515 UTC [17879] LOG:  disconnection: session time: 0:00:00.016 user=root database=postgres host=127.0.0.1 port=39368
2024-01-19 08:38:37.517 UTC [17880] LOG:  connection received: host=127.0.0.1 port=39380
2024-01-19 08:38:37.521 UTC [17880] LOG:  connection authorized: user=root database=steampipe application_name=steampipe_service_e6fe SSL enabled (protocol=TLSv1.2, cipher=ECDHE-RSA-AES256-GCM-SHA384, bits=256)
2024-01-19 08:38:37.597 UTC [17888] LOG:  connection received: host=127.0.0.1 port=39384
2024-01-19 08:38:37.603 UTC [17888] LOG:  connection authorized: user=root database=steampipe application_name=steampipe_service_e6fe SSL enabled (protocol=TLSv1.2, cipher=ECDHE-RSA-AES256-GCM-SHA384, bits=256)
2024-01-19 08:38:37.606 UTC [17880] LOG:  disconnection: session time: 0:00:00.089 user=root database=steampipe host=127.0.0.1 port=39380
2024-01-19 08:38:37.674 UTC [17888] ERROR:  relation "steampipe_internal.steampipe_connection" does not exist at character 15
2024-01-19 08:38:37.674 UTC [17888] STATEMENT:  select * FROM steampipe_internal.steampipe_connection 
2024-01-19 08:38:37.674 UTC [17888] ERROR:  relation "steampipe_internal.steampipe_connection_state" does not exist at character 15
2024-01-19 08:38:37.674 UTC [17888] STATEMENT:  select * FROM steampipe_internal.steampipe_connection_state 
2024-01-19 08:38:37.750 UTC [17896] LOG:  connection received: host=127.0.0.1 port=39398
2024-01-19 08:38:37.755 UTC [17896] LOG:  connection authorized: user=root database=steampipe application_name=steampipe_service_e6fe SSL enabled (protocol=TLSv1.2, cipher=ECDHE-RSA-AES256-GCM-SHA384, bits=256)
2024-01-19 08:38:37.763 UTC [17897] LOG:  connection received: host=127.0.0.1 port=39404
2024-01-19 08:38:37.768 UTC [17897] LOG:  connection authorized: user=root database=steampipe application_name=steampipe_service_e6fe SSL enabled (protocol=TLSv1.2, cipher=ECDHE-RSA-AES256-GCM-SHA384, bits=256)
2024-01-19 08:38:37.774 UTC [17888] LOG:  disconnection: session time: 0:00:00.177 user=root database=steampipe host=127.0.0.1 port=39384
2024-01-19 08:38:37.842 UTC [17907] LOG:  connection received: host=127.0.0.1 port=39420
2024-01-19 08:38:37.846 UTC [17907] LOG:  connection authorized: user=root database=steampipe application_name=steampipe_service_7a03 SSL enabled (protocol=TLSv1.2, cipher=ECDHE-RSA-AES256-GCM-SHA384, bits=256)
2024-01-19 08:38:37.868 UTC [17909] LOG:  connection received: host=127.0.0.1 port=39426
2024-01-19 08:38:37.873 UTC [17909] LOG:  connection authorized: user=steampipe database=steampipe application_name=steampipe_client_e6fe SSL enabled (protocol=TLSv1.2, cipher=ECDHE-RSA-AES256-GCM-SHA384, bits=256)
2024-01-19 08:38:37.875 UTC [17910] LOG:  connection received: host=127.0.0.1 port=39440
2024-01-19 08:38:37.880 UTC [17910] LOG:  connection authorized: user=steampipe database=steampipe application_name=steampipe_client_system_e6fe SSL enabled (protocol=TLSv1.2, cipher=ECDHE-RSA-AES256-GCM-SHA384, bits=256)
2024-01-19 08:38:37.886 UTC [17911] LOG:  connection received: host=127.0.0.1 port=39456
2024-01-19 08:38:37.892 UTC [17911] LOG:  connection authorized: user=steampipe database=steampipe application_name=steampipe_client_system_e6fe SSL enabled (protocol=TLSv1.2, cipher=ECDHE-RSA-AES256-GCM-SHA384, bits=256)
2024-01-19 08:38:47.632 UTC [17897] LOG:  could not receive data from client: Connection reset by peer
2024-01-19 08:38:47.632 UTC [17896] LOG:  could not receive data from client: Connection reset by peer
2024-01-19 08:38:47.632 UTC [17897] LOG:  disconnection: session time: 0:00:09.868 user=root database=steampipe host=127.0.0.1 port=39404
2024-01-19 08:38:47.632 UTC [17896] LOG:  disconnection: session time: 0:00:09.881 user=root database=steampipe host=127.0.0.1 port=39398
2024-01-19 08:39:06.031 UTC [17910] LOG:  disconnection: session time: 0:00:28.155 user=steampipe database=steampipe host=127.0.0.1 port=39440
2024-01-19 08:39:06.031 UTC [17909] LOG:  disconnection: session time: 0:00:28.162 user=steampipe database=steampipe host=127.0.0.1 port=39426
2024-01-19 08:39:06.031 UTC [17911] LOG:  disconnection: session time: 0:00:28.145 user=steampipe database=steampipe host=127.0.0.1 port=39456
2024-01-19 08:39:06.034 UTC [18265] LOG:  connection received: host=127.0.0.1 port=46506
2024-01-19 08:39:06.040 UTC [18265] LOG:  connection authorized: user=root database=steampipe application_name=steampipe_service_e6fe SSL enabled (protocol=TLSv1.2, cipher=ECDHE-RSA-AES256-GCM-SHA384, bits=256)
2024-01-19 08:39:06.044 UTC [18265] LOG:  disconnection: session time: 0:00:00.010 user=root database=steampipe host=127.0.0.1 port=46506
2024-01-19 08:39:06.046 UTC [17907] LOG:  disconnection: session time: 0:00:28.204 user=root database=steampipe host=127.0.0.1 port=39420
2024-01-19 08:39:07.048 UTC [17869] LOG:  received smart shutdown request
2024-01-19 08:39:07.051 UTC [17869] LOG:  background worker "logical replication launcher" (PID 17877) exited with exit code 1
2024-01-19 08:39:07.051 UTC [17872] LOG:  shutting down
2024-01-19 08:39:07.107 UTC [17869] LOG:  database system is shut down

**Comment by ManojDhanorkar** [comment] 2024-01-21 06:59
I also saw errors similar to https://github.com/turbot/steampipe-plugin-aws/issues/2057 .. Will use the new version ( v0.129.0 ) of plugin and see if issue get resolved.

**Comment by ManojDhanorkar** [comment] 2024-01-22 03:52
looks hang issue is now resolved with new version. 

However network-lb failed with below error. Below query gives error. 

select name,scheme,dns_name,tags_src,title,region,account_id from aws_ec2_network_load_balancer

Error:<connection> : table 'aws_ec2_network_load_balancer' column 'tags' requires hydrate data from getAwsEc2NetworkLoadBalancerTags, which failed with error operation error Elastic Load Balancing v2: DescribeTags, exceeded maximum number of attempts, 9, https response error StatusCode: 400, RequestID: c766f62c-6cfb-4cc4-b733-4f82f1febf20, api error Throttling: Rate exceeded.
 (SQLSTATE HV000)

**Comment by ParthaI** [comment] 2024-01-22 05:15
Hello, @ManojDhanorkar, Apologize for the inconvenience.

There was a bug with Steampipe AWS plugin version `v0.128.0`, which has been fixed with `v0.129.0`. 

> Error: : table 'aws_ec2_network_load_balancer' column 'tags' requires hydrate data from getAwsEc2NetworkLoadBalancerTags, which failed with error operation error Elastic Load Balancing v2: DescribeTags, exceeded maximum number of attempts, 9, https response error StatusCode: 400, RequestID: c766f62c-6cfb-4cc4-b733-4f82f1febf20, api error Throttling: Rate exceeded.
(SQLSTATE HV000)

For the above error, it looks like the API is hitting the maximum limit error. Could you please configure the `max_error_retry_attempts` and `min_error_retry_delay` in your connection config with a higher value and please give it a try again. Doc ref: https://hub.steampipe.io/plugins/turbot/aws#configuration

Please let us know if you are still running into the issues.

Thank you!

**Comment by ManojDhanorkar** [comment] 2024-01-22 08:45
Thanks. What could be reason for hitting the limit ?  Is it due to large results or something else. I think the result size is not too big. May be 1 or 2K

**Comment by ManojDhanorkar** [comment] 2024-01-24 08:22
Thanks for suggestion. _ have set max_error_retry_attempts to 15. It looks to be working now_.

**Comment by ParthaI** [comment] 2024-01-24 08:32
Thank you, @ManojDhanorkar, for confirming and I'm pleased to know the queries are working properly. It seems the issue is now resolved, so I am closing it for the moment. However, should you come across any more issues, please don't hesitate to reopen it.

Thanks again!

**Closed by ParthaI** 2024-01-24 08:32 UTC
Labels: bug
