### ISSUE TITLE
Route53 Zones return 403 when using aggregators

### ISSUE THREAD

**Issue by jchrisfarris** [turbot/steampipe-plugin-aws#1373] opened 2022-11-01 22:34 UTC
**Describe the bug**
403 Errors when querying a aws_route53_record table from an account other than the owner. [This query](https://hub.steampipe.io/plugins/turbot/aws/tables/aws_route53_record#list-all-records-in-all-zones) in the Hub documentation throws errors

**Steampipe version (`steampipe -v`)**
steampipe version 0.17.0-rc.2

**Plugin version (`steampipe plugin list`)**
hub.steampipe.io/plugins/turbot/aws@latest | 0.80.0

**To reproduce**

Setup two AWS accounts each with a hosted_zone, and then an aggregate of the two accounts in the front of the search path.

```sql
select
  r.name,
  r.type,
  r.records,
  r.alias_target
from
  aws_route53_zone as z,
  aws_route53_record as r
where
  r.zone_id = z.id ;
```
This error is returned multiple times:
```
	operation error Route 53: ListResourceRecordSets, https response error StatusCode: 403, RequestID: 67e26688-cd22-4cbf-bd24-331669217f5c, api error AccessDenied: User: arn:aws:sts::xxxx:assumed-role/xxx-audit/steampipe is not authorized to access this resource
```

**Expected behavior**
When querying a hosted_zone that's outside the account that can list it, the 403 should be ignored. 

**Additional context**
I can provide access to a test environment.

**Comment by cbruno10** [comment] 2023-06-12 16:12
Not stale

**Comment by bigdatasourav** [comment] 2023-06-16 08:05
@jchrisfarris, sorry for the delayed response on this one.

I was able to reproduce the issue. Followed the below steps - 
Aggregated connection with two accounts, each containing a hosted zone - 
```
> select account_aliases, arn, organization_id from aws_account
+-----------------+------------------------+-----------------+
| account_aliases | arn                    | organization_id |
+-----------------+------------------------+-----------------+
| ["nagraj-aaa"]  | arn:aws:::63212344528 | o-c3awwerewrd52    |
| ["test-aab]              | arn:aws:::5312323232495 | o-c3awrewrewrd52    |
+-----------------+------------------------+-----------------+
```
```
> select
  r.name,
  r.type,
  r.records,
  r.alias_target
from
  aws_route53_zone as z,
  aws_route53_record as r
where
  r.zone_id = z.id ;

Error: operation error Route 53: ListResourceRecordSets, https response error StatusCode: 403, RequestID: 672ca103-5bb3-43af-98ea-6ddb3bc3052d, api error AccessDenied: User: arn:aws:iam::63212323434528:user/sourav is not authorized to access this resource (SQLSTATE HV000)

+--------------------+-------+-----------------------------------------------------------------------------------------------------+--------------+
| name               | type  | records                                                                                             | alias_target |
+--------------------+-------+-----------------------------------------------------------------------------------------------------+--------------+
| testaab.com.       | SOA   | ["ns-1536.awsdns-00.co.uk. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400"]                 | <null>       |
| test1.testaab.com. | CNAME | ["yahoo.com"]                                                                                       | <null>       |
| testaab.com.       | NS    | ["ns-1536.awsdns-00.co.uk.","ns-0.awsdns-00.com.","ns-1024.awsdns-00.org.","ns-512.awsdns-00.net."] | <null>       |
+--------------------+-------+-----------------------------------------------------------------------------------------------------+--------------+
```

Please use ignore_error_codes in each connection in your spc file and Let me know if that resolves the issue.

Here is an example of a set of connections with ignore_error_codes -
```
connection "aws_nagraj" {
profile   = "default1"
regions = ["*"]
plugin    = "aws" 
ignore_error_codes = ["AccessDeniedException","AccessDenied"]               
}

connection "aws_aab" {
profile   = "default2"
regions = ["*"]
plugin    = "aws" 
ignore_error_codes = ["AccessDeniedException","AccessDenied"]               
}

connection "aws" {
  plugin      = "aws"
  type        = "aggregator"
  connections = ["aws_nagraj","aws_aab"]
}
```

Here is the output after using the ignore_error_codes in each connection - 
```
> select
  r.name,
  r.type,
  r.records,
  r.alias_target
from
  aws_route53_zone as z,
  aws_route53_record as r
where
  r.zone_id = z.id ;
+-----------------------+-------+-------------------------------------------------------------------------------------------------------+--------------+
| name                  | type  | records                                                                                               | alias_target |
+-----------------------+-------+-------------------------------------------------------------------------------------------------------+--------------+
| test-nag\100test.com. | NS    | ["ns-1412.awsdns-48.org.","ns-522.awsdns-01.net.","ns-355.awsdns-44.com.","ns-1734.awsdns-24.co.uk."] | <null>       |
| test-nag\100test.com. | SOA   | ["ns-1412.awsdns-48.org. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400"]                     | <null>       |
| testaab.com.          | NS    | ["ns-1536.awsdns-00.co.uk.","ns-0.awsdns-00.com.","ns-1024.awsdns-00.org.","ns-512.awsdns-00.net."]   | <null>       |
| testaab.com.          | SOA   | ["ns-1536.awsdns-00.co.uk. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400"]                   | <null>       |
| test1.testaab.com.    | CNAME | ["yahoo.com"]                                                                                         | <null>       |
+-----------------------+-------+-------------------------------------------------------------------------------------------------------+--------------+
```

**Comment by captainfalcon23** [comment] 2023-06-19 11:31
Hi @misraved , tested and the fix works. I feel like it's not the _correct_ fix, as we are just concealing an error condition and I think steampipe/the plugin should have some smarts to handle this scenario

**Comment by bigdatasourav** [comment] 2023-06-21 09:43
Hey @captainfalcon23, here are some Route53 API responses on the different scenarios - 

- AWS Route 53 returns this error when given a zone ID into GetHostedZone for a zone that doesn’t exist:

An error occurred (NoSuchHostedZone) when calling the GetHostedZone operation: No hosted zone found with ID: Z103678123456OLJ00PNO

- But when given a zone ID for a zone that exists but you don’t have access to, e.g., the zone is in another AWS account:

An error occurred (AccessDenied) when calling the GetHostedZone operation: User: arn:aws:iam::123456789012:user/test is not authorized to access this resource

Because the error message cannot help us determine if the zone is from another account and the zone ID contains no account info, we’ve chosen to have the table ignore AccessDenied errors for its GetConfig to provide a smoother querying experience so that no rows will be returned instead of a fatal error.

**Comment by captainfalcon23** [comment] 2023-06-21 23:49
Hey @bigdatasourav ,
Yep that makes sense. However, it also means Cloudtrail fills up with lots of denied exceptions. Perhaps a better way to handle it is by adding an additional "where" condition to the join, e.g. from the example in the OP:
```
select
  r.name,
  r.type,
  r.records,
  r.alias_target
from
  aws_route53_zone as z,
  aws_route53_record as r
where
  r.zone_id = z.id 
and r._ctx = z._ctx; <----------------
```

I haven't tested this but I assume this might also work.

**Comment by bigdatasourav** [comment] 2023-06-22 07:52
@captainfalcon23, thank you for providing the workaround. I have tested it, but unfortunately, the query did not work as expected.

```
> select
  r.name,
  r.type,
  r.records,
  r.alias_target
from
  aws_route53_zone as z,
  aws_route53_record as r
where
  r.zone_id = z.id 
and r._ctx = z._ctx;

Error: operation error Route 53: ListResourceRecordSets, https response error StatusCode: 403, RequestID: 198b463e-44b9-4550-a6ec-ee3dc0a1045e, api error AccessDenied: User: arn:aws:iam::123456789:user/turbot/account/federated/sourav is not authorized to access this resource (SQLSTATE HV000)

+-----------------------+------+-----------------------------------------------------------------------------------+--------------+
| name                  | type | records                                                                           | alias_target |
+-----------------------+------+-----------------------------------------------------------------------------------+--------------+
| test-nag\100test.com. | SOA  | ["ns-1412.awsdns-48.org. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400"] | <null>       |
+-----------------------+------+-----------------------------------------------------------------------------------+--------------+

```

**Comment by captainfalcon23** [comment] 2023-06-22 23:51
Ok yep, I tested also and a few other ways of writing the query, but I think the problem is, steampipe isn't smart enough (at least in this context/for these tables) to look at the underlying connections in the aggregation and using only the results for each underlying connection in the clause.

However, I am thinking now @bigdatasourav , looking at your previous comment:
`AWS Route 53 returns this error when given a zone ID into GetHostedZone for a zone that doesn’t exist:
An error occurred (NoSuchHostedZone) when calling the GetHostedZone operation: No hosted zone found with ID: Z103678123456OLJ00PNO

But when given a zone ID for a zone that exists but you don’t have access to, e.g., the zone is in another AWS account:
An error occurred (AccessDenied) when calling the GetHostedZone operation: User: arn:aws:iam::123456789012:user/test is not authorized to access this resource`

So I assume you are using "GetHostedZone" to populate the table "aws_route53_record". So, when the query is made, before running "GetHostedZone", why not run "ListHostedZones" and check first if the requested zone in the join is actually in that account, and if not, don't try to get hosted zones which we know don't exist, and if it is, continue.

The other problem to solve is, if a user **legitimately** does not have access to call GetHostedZone, I think we would not want to swallow that error. 

I think Route53 is a bit special I think, and I don't think I've come across this scenario with any other services :)

**Comment by jchrisfarris** [comment] 2023-06-22 23:58
I agree with Falcon here - if the Hosted Zone doesn't exist return that. If I'm doing a join with multiple connections, I need the ability to only query the zone from the connection that is the owner of the zone. I shouldn't have to hack up my connection files to run this one query, and I would not want to blindly ignore AccessDenied errors in day-to-day usage. 

Also, would that solution even work in SPC? 

@e-gineer mentioned that there was some solution implemented for S3 Buckets (also a global namespace for unique identifiers) that could/should be used here. I no longer have access to that conversation, but you might ping him for more details.

**Comment by bigdatasourav** [comment] 2023-06-27 05:46
Hey @captainfalcon23, apologies for the confusion; the API ListResourceRecordSets is used in aws_route53_record, where zone_id is a required input parameter. This API returns the below error - 

```
Error: operation error Route 53: ListResourceRecordSets, https response error StatusCode: 403, RequestID: 198b463e-44b9-4550-a6ec-ee3dc0a1045e, api error AccessDenied: User: arn:aws:iam::123456789:user/turbot/account/federated/sourav is not authorized to access this resource (SQLSTATE HV000)
```

**Comment by bigdatasourav** [comment] 2023-06-27 06:49
I have raised a [PR](https://github.com/turbot/steampipe-plugin-aws/pull/1799) which may solve the problem. Updated the table to use ParentHydrate listHostedZones; zone_id will be optional. All existing queries will work, so it should not be a breaking change.

```
> select name, type, records, alias_target from aws_route53_record
+-----------------------+-------+-------------------------------------------------------------------------------------------------------+--------------+
| name                  | type  | records                                                                                               | alias_target |
+-----------------------+-------+-------------------------------------------------------------------------------------------------------+--------------+
| test-nag\100test.com. | SOA   | ["ns-1412.awsdns-48.org. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400"]                     | <null>       |
| test-nag\100test.com. | NS    | ["ns-1412.awsdns-48.org.","ns-522.awsdns-01.net.","ns-355.awsdns-44.com.","ns-1734.awsdns-24.co.uk."] | <null>       |
| testaab.com.          | NS    | ["ns-1536.awsdns-00.co.uk.","ns-0.awsdns-00.com.","ns-1024.awsdns-00.org.","ns-512.awsdns-00.net."]   | <null>       |
| test1.testaab.com.    | CNAME | ["yahoo.com"]                                                                                         | <null>       |
| testaab.com.          | SOA   | ["ns-1536.awsdns-00.co.uk. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400"]                   | <null>       |
+-----------------------+-------+-------------------------------------------------------------------------------------------------------+--------------+
```

```
> select
  r.name,
  r.type,
  r.records,
  r.alias_target
from
  aws_route53_zone as z,
  aws_route53_record as r
where
  r.zone_id = z.id
+-----------------------+-------+-------------------------------------------------------------------------------------------------------+--------------+
| name                  | type  | records                                                                                               | alias_target |
+-----------------------+-------+-------------------------------------------------------------------------------------------------------+--------------+
| test-nag\100test.com. | SOA   | ["ns-1412.awsdns-48.org. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400"]                     | <null>       |
| test-nag\100test.com. | NS    | ["ns-1412.awsdns-48.org.","ns-522.awsdns-01.net.","ns-355.awsdns-44.com.","ns-1734.awsdns-24.co.uk."] | <null>       |
| test1.testaab.com.    | CNAME | ["yahoo.com"]                                                                                         | <null>       |
| testaab.com.          | SOA   | ["ns-1536.awsdns-00.co.uk. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400"]                   | <null>       |
| testaab.com.          | NS    | ["ns-1536.awsdns-00.co.uk.","ns-0.awsdns-00.com.","ns-1024.awsdns-00.org.","ns-512.awsdns-00.net."]   | <null>       |
+-----------------------+-------+-------------------------------------------------------------------------------------------------------+--------------+
```

@captainfalcon23 Could you please try it out and let us know your feedback?

@e-gineer @cbruno10 Please share your thoughts.

**Comment by captainfalcon23** [comment] 2023-06-28 00:55
Hi @bigdatasourav 
Tested this branch and it seems to work, but it is slowwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww. For example:

(This aggregation aws_all_exclude_blah_childs includes 6 aws accounts)

```
time steampipe query 'select count(*) from (select   r.name,  r.type,  r.records,  r.alias_target from   aws_all_exclude_blah_childs.aws_route53_zone as z,   aws_all_exclude_blah_childs.aws_route53_record as r where  r.zone_id = z.id) inside'

+-------+
| count |
+-------+
| 1673  |
+-------+

real    7m59.667s
user    0m45.230s
sys     0m4.325s
```

Comparing this to my gitlab job (using same accounts +   ignore_error_codes = ["AccessDeniedException","AccessDenied"] work around, which also needs to do all these presteps:
* setup the docker executor runner environment (30s-1min)
* install awscli (30sec)
* install steampipe (15-30sec)
* install plugins: steampipe, aws, csv (30sec)
* copy in all the cred files and set them up (5sec)
* pip install 1 package for some python code (15sec)
* total time on presteps 115sec, lets say 2min

And after all that, run the steampipe query. The total time for the job was 5min 58sec.

So the query itself took approx 3min 58 sec, compared to almost double that from my local.

**Comment by bigdatasourav** [comment] 2023-06-28 06:36
Hey @captainfalcon23, zone_id is no longer a mandatory parameter in the above branch. So we do not need to join tables to fetch records for all zones. Could you please try the below -
`select name,  type,  records,  alias_target from  aws_all_exclude_blah_childs.aws_route53_record`

**Comment by captainfalcon23** [comment] 2023-06-28 22:51
Hey @bigdatasourav 
Wowiee!! What a difference!! Completed in 6 seconds!!
```
$ time steampipe query 'select count(*) from (select name,  type,  records,  alias_target from   aws_all_exclude_sonet_childs.aws_route53_record) inside'
+-------+
| count |
+-------+
| 1673  |
+-------+

real    0m6.942s
user    0m2.959s
sys     0m0.634s

```

I think that solves this issue, once merged, this can be closed off. Thanks heaps for all your help :)

**Closed** 2023-07-04 05:33 UTC
Labels: bug
