### ISSUE TITLE
`select * from aws_backup_vault` fails with '{vaultname} has no associated POLICY'

### ISSUE THREAD

**Issue by Veetaha** [turbot/steampipe-plugin-aws#2032] opened 2023-12-21 02:14 UTC
**Describe the bug**
I'm running steampipe in service mode with the following SQL query:
```sql
select * from aws_backup_vault;
```
It fails with the following error returned from the Postgres DB:
```
rpc error: code = Unknown desc = aws: operation error Backup: GetBackupVaultNotifications,
https response error StatusCode: 400, RequestID: 9ccbaa41-9dde-42b7-9516-488cb9657e2c,
api error ERROR_2106: Failed reading notifications from database for Backup vault
```
This error message doesn't actually explain why the query fails, but if you open `~/.steampipe/logs/plugin-{date}.log` you'll find the cause:

```
aws_backup_vault.getAwsBackupVaultAccessPolicy: api_error="operation error Backup: GetBackupVaultAccessPolicy,
https response error StatusCode: 400, RequestID: 902e604d-ef79-4a98-b8f2-3126bfc595a2, ResourceNotFoundException:
Backup Vault arn:aws:backup:us-east-2:528005273388:backup-vault:Default has no associated POLICY"
```

**Steampipe version (`steampipe -v`)**
`v0.21.2`

**Plugin version (`steampipe plugin list`)**
`v0.125.0`

**To reproduce**
Just make sure you have a default AWS Backup vault with no additional configuration or create a new clean one with the following AWS CLI command:
```
aws backup create-backup-vault --backup-vault-name test-vault
```
Run
```
steampipe query "select * from aws_backup_vault"
```

**Expected behavior**
The operation should not fail, it should gracefully handle the "{vault} has no associated POLICY" error from `GetBackupVaultAccessPolicy` and set the `policy/policy_std` to `null` in this case.

**Comment by ParthaI** [comment] 2023-12-21 15:19
Hello @Veetaha, sorry to hear that you're experiencing this issue.

I was able to reproduce the error by running the given query.

The actual error was populating the value for the columns `backup_vault_events` and   `sns_topic_arn`. I have pushed the fix in this [PR](https://github.com/turbot/steampipe-plugin-aws/pull/2033).

> aws_backup_vault.getAwsBackupVaultAccessPolicy: api_error="operation error Backup: GetBackupVaultAccessPolicy,
https response error StatusCode: 400, RequestID: 902e604d-ef79-4a98-b8f2-3126bfc595a2, ResourceNotFoundException:
Backup Vault arn:aws:backup:us-east-2:528005273388:backup-vault:Default has no associated POLICY"

The message above was a logging statement mistakenly placed within the table's code. I have since reorganized the code appropriately.

Before fix:

```
> select * from aws_backup_vault;

Error: aws: operation error Backup: GetBackupVaultNotifications, https response error StatusCode: 400, RequestID: 4a773d3d-b31f-4d2b-8aba-eebbd4cc21eb, api error ERROR_2106: Failed reading notifications from database for Backup vault (SQLSTATE HV000)

+------+-----+---------------+--------------------+--------------------+---------------------------+---------------+--------+------------+---------------------+-------+------+------+-----------+--------+------------+------+
| name | arn | creation_date | creator_request_id | encryption_key_arn | number_of_recovery_points | sns_topic_arn | policy | policy_std | backup_vault_events | title | tags | akas | partition | region | account_id | _ctx |
+------+-----+---------------+--------------------+--------------------+---------------------------+---------------+--------+------------+---------------------+-------+------+------+-----------+--------+------------+------+
+------+-----+---------------+--------------------+--------------------+---------------------------+---------------+--------+------------+---------------------+-------+------+------+-----------+--------+------------+------+

Time: 4.0s.

```

After fix: 

```
> select * from aws_backup_vault;
+--------------------------------+------------------------------------------------------------------------------------+---------------------------+--------------------------------------------------+----------------------------------------------------------------------->
| name                           | arn                                                                                | creation_date             | creator_request_id                               | encryption_key_arn                                                    >
+--------------------------------+------------------------------------------------------------------------------------+---------------------------+--------------------------------------------------+----------------------------------------------------------------------->
| Default                        | arn:aws:backup:ap-south-1:223322332233:backup-vault:Default                        | 2021-05-27T16:11:00+05:30 | Default                                          | arn:aws:kms:ap-south-1:223322332233:key/c5c6dbb8-d6d7-46e4-8b18-30cd70>
| aws/efs/automatic-backup-vault | arn:aws:backup:ap-south-1:223322332233:backup-vault:aws/efs/automatic-backup-vault | 2021-04-08T17:30:52+05:30 | aws/efs/automatic-backup-223322332233-ap-south-1 | arn:aws:kms:ap-south-1:223322332233:key/c5c6dbb8-d6d7-46e4-8b18-30cd70>
| Default                        | arn:aws:backup:eu-west-2:223322332233:backup-vault:Default                         | 2023-12-21T12:39:46+05:30 | Default                                          | arn:aws:kms:eu-west-2:223322332233:key/a451cbcd-5b8f-499d-9f17-e6d6a7b>
| Default                        | arn:aws:backup:us-west-2:223322332233:backup-vault:Default                         | 2022-08-10T19:30:54+05:30 | Default                                          | arn:aws:kms:us-west-2:223322332233:key/98d66961-3e3c-4ce2-94f8-5cb38b3>
| Default                        | arn:aws:backup:us-east-1:223322332233:backup-vault:Default                         | 2021-10-26T12:28:12+05:30 | Default                                          | arn:aws:kms:us-east-1:223322332233:key/80e0e625-2267-4471-8ff4-bb71f99>
| aws/efs/automatic-backup-vault | arn:aws:backup:us-east-1:223322332233:backup-vault:aws/efs/automatic-backup-vault  | 2022-01-10T18:50:39+05:30 | aws/efs/automatic-backup-223322332233-us-east-1  | arn:aws:kms:us-east-1:223322332233:key/80e0e625-2267-4471-8ff4-bb71f99>
| Default                        | arn:aws:backup:us-east-2:223322332233:backup-vault:Default                         | 2023-12-21T17:45:22+05:30 | Default                                          | arn:aws:kms:us-east-2:223322332233:key/af5d6efa-4faa-4bb1-8e47-f563e09>
+--------------------------------+------------------------------------------------------------------------------------+---------------------------+--------------------------------------------------+-----------------------------------------------------------------------
```

Please let me know if you are encountering any other issues.

Thank you!

**Closed** 2024-01-08 10:53 UTC
Labels: bug
