### ISSUE TITLE
Add account_id and region to aws_msk_cluster

### ISSUE THREAD

**Issue by p5** [turbot/steampipe-plugin-aws#1886] opened 2023-09-04 19:42 UTC
**Describe the bug**
The current values for both `account_id` and `region` for `aws_msk_cluster` resources are `null`.

**Steampipe version (`steampipe -v`)**
v0.20.9

**Plugin version (`steampipe plugin list`)**
v0.117.0

**To reproduce**
To reproduce this issue, run the following query against any account containing an MSK cluster:
```
SELECT
  account_id,
  cluster_name,
  region,
  arn
FROM
  aws_msk_cluster;
```

**Expected behavior**
These values should be populated with the AWS Account ID and Region where the MSK cluster is hosted.

**Additional context**

**Comment by misraved** [comment] 2023-09-05 05:22
Apologies for the inconvenience @p5 and welcome to Steampipe 👋 !!

On running the above query, do you get results for the columns `cluster_name` and `arn`? Also are you able to query `account_id` and `region` for other tables like `aws_ec2_instance` etc.?

**Comment by p5** [comment] 2023-09-05 05:35
> Apologies for the inconvenience @p5 and welcome to Steampipe 👋 !!
> 
> On running the above query, do you get results for the columns `cluster_name` and `arn`? Also are you able to query `account_id` and `region` for other tables like `aws_ec2_instance` etc.?

Thanks for the response!

Yes, I do receive results for the `cluster_name`  and `arn` but get `<null>` for `account_id` and `region`.

I am able to get this information from querying other resources in the account.  

I am certain this is not due to a lack of permissions since I have tried with both the ReadOnly and AdministratorAccess managed policies.

**Comment by misraved** [comment] 2023-09-07 13:14
Thanks for the response @p5 👍.

We have managed to replicate the issue.

@ParthaI is currently working to get a fix out for this bug 👍.

**Comment by p5** [comment] 2023-09-07 13:15
Great to hear!  Thank you for looking into it!

**Comment by ParthaI** [comment] 2023-09-28 14:40
Dear @graza-io,

I wanted to express my gratitude for providing clarification.

@misraved and I recently had a discussion on this matter earlier, and I observed that in our most recent Steampipe SDK version, `v5.6.0`, the issue has been resolved, and we are now able to retrieve the `account_id` and `region` values from the table.

```
> select arn, account_id, region from aws_msk_cluster
+-----------------------------------------------------------------------------------------------------+--------------+------------+
| arn                                                                                                 | account_id   | region     |
+-----------------------------------------------------------------------------------------------------+--------------+------------+
| arn:aws:kafka:ap-south-1:xxxxxxxxxxxx:cluster/demo-cluster-1/1afa400c-102f-4a53-b0f9-879c1938f48d-2 | xxxxxxxxxxxx | ap-south-1 |
+-----------------------------------------------------------------------------------------------------+--------------+------------+

```
@graza-io, @misraved ,  I genuinely appreciate your efforts in addressing this issue. I had noticed it earlier but was unable to pinpoint the root cause of the error. Your assistance is greatly valued. Thank You!

**Comment by graza-io** [comment] 2023-09-28 16:32
Can confirm I observe the same behaviour on upgraded SDK.

**Comment by misraved** [comment] 2023-10-02 15:11
Addressed in https://github.com/turbot/steampipe-plugin-aws/blob/main/CHANGELOG.md#v01200-2023-10-02

**Closed by misraved** 2023-10-02 15:11 UTC
Labels: bug
