### ISSUE TITLE
Encountered errors on queries running on aggregated connection

### ISSUE THREAD

**Issue by sivashankar-tomtom** [turbot/steampipe-plugin-aws#1953] opened 2023-11-02 12:50 UTC
**Describe the bug**
I have started using steampipe DB as a service in our organization. I encountered resource not found exception when running queries on an aggregated connection. 

**Steampipe version (`steampipe -v`)**
Example: v0.21.1

**Plugin version (`steampipe plugin list`)**
Example: hub.steampipe.io/plugins/turbot/aws@0.121.0

**To reproduce**
When performing a `select * from aws.aws_s3_bucket` query on an aggregated connection, the following errors occur and steampipe does not return any result:
```
SQL Error [HV000]: ERROR: rpc error: code = Unknown desc = 
	operation error S3: GetBucketLocation, https response error StatusCode: 404, RequestID: XXXXXX, HostID: abcdfgef, api error NoSuchBucket: The specified bucket does not exist
```
Similarly while performing `select * from aws.aws_ec2_instance`
SQL Error [HV000]: ERROR: rpc error: code = Unknown desc = 
	operation error EC2: GetLaunchTemplateData, https response error StatusCode: 400, RequestID: xxxxxxx, api error InvalidInstanceID.NotFound: The instance ID 'i-12345558' does not exist

**Expected behavior**
I would expect the query to show results instead of throwing resource not found exception. Either steampipe to wait for the resource to be created or ignore the ephemeral resources.

**Comment by rajlearner17** [comment] 2023-11-03 12:09
@sivashankar-tomtom 
While @ParthaI is trying to reproduce this issue for S3, I am sharing my experience in EC2. Please execute this query and check if you get a response right. 

Is there any case where your instance is getting terminated dynamically by some process while executing the query?

```sql
select count(*) from aws_ec2_instance where (instance_status -> 'InstanceState' ->> 'Name') != 'terminated'
```

**Comment by sivashankar-tomtom** [comment] 2023-11-03 12:22
@rajlearner17 I am running the queries on an aggregated connection. There are more than 4K instances running in the organization. Its highly possible that some of the instances might be terminated/newly-created manually or by ASG or any other pipeline while executing the query.

**Comment by rajlearner17** [comment] 2023-11-03 12:34
Would it be possible for you to update the query from

`select * from aws.aws_ec2_instance`, >> to >> `select * from aws.aws_ec2_instance where (instance_status -> 'InstanceState' ->> 'Name') != 'terminated'`(Pls note `*` will result in delay)

IMO, we may need to include this filter to avoid this error occurrence for now. I will let other members give feedback.

**Comment by ParthaI** [comment] 2023-11-06 11:08
Hello @sivashankar-tomtom, I would like to confirm if you had the opportunity to review the query recommended by @rajlearner17 for the EC2 Instance table. 
Did it assist you in resolving the issue with the `aws_ec2_instance` table?

I explored the `aws_s3_bucket` table to reproduce the issue but was unable to do so. I repeatedly tested the query with an aggregated connection and encountered no issues; the results were consistent every time.

I have the following setup:
Steampipe CLI version: `v0.21.1`
AWS plugin version: `v0.121.0`

```
> select * from aws_all.aws_s3_bucket
+-----------------------------------------------------------------+------------------------------------------------------------------------------+---------------------------+-------------------------+--------------------+-----------------------+-------------------+---->
| name                                                            | arn                                                                          | creation_date             | bucket_policy_is_public | versioning_enabled | versioning_mfa_delete | block_public_acls | blo>
+-----------------------------------------------------------------+------------------------------------------------------------------------------+---------------------------+-------------------------+--------------------+-----------------------+-------------------+---->
| capcha7.2                                                       | arn:aws:s3:::capcha7.2                                                       | 2020-08-27T14:51:12+05:30 | false                   | true               | false                 | true              | tru>
| destination-bucket-name-778899999                               | arn:aws:s3:::destination-bucket-name-778899999                               | 2023-07-20T17:26:35+05:30 | false                   | true               | false                 | true              | tru>
| aws-cloudtrail-logs-222222222222-5edd7283                       | arn:aws:s3:::aws-cloudtrail-logs-222222222222-5edd7283                       | 2023-06-22T18:09:07+05:30 | false                   | false              | false                 | true              | t


> select * from aws_all.aws_s3_bucket
+-----------------------------------------------------------------+------------------------------------------------------------------------------+---------------------------+-------------------------+--------------------+-----------------------+-------------------+---->
| name                                                            | arn                                                                          | creation_date             | bucket_policy_is_public | versioning_enabled | versioning_mfa_delete | block_public_acls | blo>
+-----------------------------------------------------------------+------------------------------------------------------------------------------+---------------------------+-------------------------+--------------------+-----------------------+-------------------+---->
| aws-security-data-lake-ap-southeast-2-4i3pnujz7bpnx72x6oheacrcx | arn:aws:s3:::aws-security-data-lake-ap-southeast-2-4i3pnujz7bpnx72x6oheacrcx | 2022-12-01T15:37:29+05:30 | false                   | false              | false                 | true              | tru>
| aws-cloudtrail-logs-333333333333-4ad784a1                       | arn:aws:s3:::aws-cloudtrail-logs-333333333333-4ad784a1                       | 2021-03-19T13:18:28+05:30 | false                   | true               | false                 | true              | tru>
| aws-security-data-lake-ap-northeast-1-yd5aigzmgod7uadzgou2d2otb | arn:aws:s3:::aws-security-data-lake-ap-northeast-1-yd5aigzmgod7uadzgou2d2otb | 2022-12-01T15:37:10+05:30 | false                   | false              | false                 | true              | tru>
| sagemaker-studio-222222222222-onpnn9esrt                        | arn:aws:s3:::sagemaker-studio-222222222222-onpnn9esrt                        | 2022-05-06T19:21:53+05:30 | false                   | false              | false                 | false             | fal>
| aws-cloudtrail-logs-222222222222-5edd7283                       | arn:aws:s3:::aws-cloudtrail-logs-222222222222-5edd7283                       | 2023-06-22T18:09:07+05:30 | false                   | false              | false                 | true              | tru>
| aab-apso1-d6lbmfze6q4e                                          | arn:aws:s3:::aab-apso1-d6lbmfze6q4e                                          | 2018-03-19T04:37:47+05:30 | false                   | true               | false                 | true              | tru>
```

I do have a couple of follow-up questions:

1. Are the queries failing for aggregated connections only, or do they also fail with single connections?
2. Could you please try the query with a single connection to check if you encounter the same error?

Thanks!

**Comment by rajlearner17** [comment] 2023-11-14 11:16
@sivashankar-tomtom, I Hope you are doing well. Can you please revert if you continuously see the same issues for EC2 and S3?

**Comment by ParthaI** [comment] 2023-11-27 05:56
Hey @sivashankar-tomtom , We are closing this issue because we have not heard from you. Please feel free to reopen the issue if you want to share or discuss anything.

**Closed by ParthaI** 2023-11-27 05:56 UTC
Labels: bug

**Comment by YifeiY** [comment] 2024-05-15 20:02
Encountering the same issue. As @sivashankar-tomtom suggested, could we explicitly handle `InvalidInstanceID.NotFound` instead of crashing the query?
