### ISSUE TITLE
Filter inspector2 findings by resource type

### ISSUE THREAD

**Issue by seanthebear** [turbot/steampipe-plugin-aws#1816] opened 2023-07-06 15:19 UTC
I would like to be able to filter findings by resource type easily. Currently I have to filter from a load of json out put and can't be confident in my results.

The resource type isn't populated in the current set up for inspector2 findings. If it were then filtering only on a resource type would be easier and cut out any potential noise from other resources.

**Comment by graza-io** [comment] 2023-07-06 16:46
@seanthebear - if you wish to filter for a specific resource type, you can pass this in as a qualifier:

```sql
select
  <fields>
 from
   aws_inspector2_finding
 where
   resource_type = <type>;
```

Based on how the table appears to be working.

**Comment by graza-io** [comment] 2023-07-14 13:26
@seanthebear - I'm closing this issue as resolved.

**Comment by ParthaI** [comment] 2023-07-19 12:51
@cbruno10 , Here are a few findings regarding this issue. Please take a look.

- The column `resource_type` is the optional qualifier in the table `aws_inspector2_finding`.
- The column `resource_type`  value is being populated from the quals Transform:   `transform.FromQual("resource_type"),`

**The query with resource_type  in where clause returning the result as expected.**

```
> select arn, finding_account_id, resource_type, description from aws_aab.aws_inspector2_finding where resource_type ='AWS_LAMBDA_FUNCTION';
+-------------------------------------------------------------------------------------+--------------------+---------------------+------------------------------------------------------------------------->
| arn                                                                                 | finding_account_id | resource_type       | description                                                             >
+-------------------------------------------------------------------------------------+--------------------+---------------------+------------------------------------------------------------------------->
| arn:aws:inspector2:ap-south-1:xxxxxxxxxxxxxx:finding/f4ca4642ad0711478b57a3fbe557d10b | xxxxxxxxxxxxxx       | AWS_LAMBDA_FUNCTION | urllib3 before 1.25.9 allows CRLF injection if the attacker controls the>
| arn:aws:inspector2:ap-south-1:xxxxxxxxxxxxxx:finding/8282a7358bc6792e907c9073fde551a9 | xxxxxxxxxxxxxx       | AWS_LAMBDA_FUNCTION | An issue was discovered in urllib3 before 1.26.5. When provided with a U>
| arn:aws:inspector2:ap-south-1:xxxxxxxxxxxxxx:finding/d613a3e2c2037a9a41ac6a1d16c9020b | xxxxxxxxxxxxxx       | AWS_LAMBDA_FUNCTION | Requests is a HTTP library. Since Requests 2.3.0, Requests has been leak>
|                                                                                     |                    |                     |                                                                         >
|                                                                                     |                    |                     |                                                                         >
| arn:aws:inspector2:ap-south-1:xxxxxxxxxxxxxx:finding/92083a47ca7f33da542263d59625b9b5 | xxxxxxxxxxxxxx       | AWS_LAMBDA_FUNCTION | Certifi is a curated collection of Root Certificates for validating the >
+-------------------------------------------------------------------------------------+--------------------+---------------------+------------------------------------------------------------------------->
```

**There are few findings regarding the caching thing:**

- At first with cache enabled run the query `select arn, finding_account_id, resource_type, description from aws_aab.aws_inspector2_finding`  (Returns the result).
- Re-run the query by passing `resource_type` in  where clause `select arn, finding_account_id, resource_type, description from aws_aab.aws_inspector2_finding where resource_type ='AWS_LAMBDA_FUNCTION'` (Do not return any result)
- By disabling the cache the both of the query returns rows.

```
> select arn, resource_type from aws_aab.aws_inspector2_finding
+-------------------------------------------------------------------------------------+---------------+
| arn                                                                                 | resource_type |
+-------------------------------------------------------------------------------------+---------------+
| arn:aws:inspector2:ap-south-1:xxxxxxxxxxxxxx:finding/92083a47ca7f33da542263d59625b9b5 | <null>        |
| arn:aws:inspector2:ap-south-1:xxxxxxxxxxxxxx:finding/8282a7358bc6792e907c9073fde551a9 | <null>        |
| arn:aws:inspector2:ap-south-1:xxxxxxxxxxxxxx:finding/f4ca4642ad0711478b57a3fbe557d10b | <null>        |
| arn:aws:inspector2:ap-south-1:xxxxxxxxxxxxxx:finding/84bd2020236a46ccbcb1a65206bc806b | <null>        |
| arn:aws:inspector2:ap-south-1:xxxxxxxxxxxxxx:finding/d613a3e2c2037a9a41ac6a1d16c9020b | <null>        |
| arn:aws:inspector2:ap-south-1:xxxxxxxxxxxxxx:finding/e0877c2ae509d9205b8b8406a397eb00 | <null>        |
| arn:aws:inspector2:ap-south-1:xxxxxxxxxxxxxx:finding/9d24bbae84bd1d0efce396a1b62336cb | <null>        |
+-------------------------------------------------------------------------------------+---------------+

Time: 6.3s. Rows fetched: 7. Hydrate calls: 0.

> select arn, finding_account_id, resource_type from aws_aab.aws_inspector2_finding where resource_type ='AWS_EC2_INSTANCE';
+-----+--------------------+---------------+
| arn | finding_account_id | resource_type |
+-----+--------------------+---------------+
+-----+--------------------+---------------+

Time: 61ms. Rows fetched: 7 (cached). Hydrate calls: 0.
```

- I believe, this is the by design, we do cache results that returns from a API call that may be list/get/hydrate API call for a single query run. 
- While we set the cache for the query `select arn, resource_type from aws_aab.aws_inspector2_finding` at that time the resource_type column value was null.
- In 2nd query `select arn, finding_account_id, resource_type from aws_aab.aws_inspector2_finding where resource_type ='AWS_EC2_INSTANCE';` we are fetching the rows from the cached result, in this case the value `AWS_EC2_INSTANCE`  in where clause is not matching with the cached result so it is returning the zero rows.
- To overcome this problem we can add CacheMatch: "exact" in key column quals configuration in list config.

If we are adding `CacheMatch: "exact"`  to key quals config, it is making API call all the time when we are using the optional qualifier  `resource_type`  in where clause and returning the rows as expected.

IMO, we should add `CacheMatch: "exact"`  to the optional key quals for that column where the column value is being populated from the quals like `Transform:   transform.FromQual("resource_type")`,.

Raised a [PR](https://github.com/turbot/steampipe-plugin-aws/pull/1847) for it. Thanks!

**Comment by cbruno10** [comment] 2023-07-25 18:20
Re-opening issue as I believe there is still an issue when filtering on `resource_type` (and potentially other optional quals as well). We need to do some additional testing in order to confirm.

**Comment by misraved** [comment] 2023-07-26 05:52
Relevant slack thread - https://steampipe.slack.com/archives/C01UECB59A7/p1677597014454359

**Comment by graza-io** [comment] 2023-09-28 07:40
I had a quick look at this and initially it appears to be behaving as expected.

Was there a specific usage pattern/approach that needs further testing?
![issue_1816](https://github.com/turbot/steampipe-plugin-aws/assets/53316123/16504584-0ad7-41ac-9098-cc97e4a276d9)

**Comment by bigdatasourav** [comment] 2023-11-06 11:20
Hey, @seanthebear, if you're still seeing this issue, please feel free to re-open this issue; we can investigate more. Thanks!

**Closed by bigdatasourav** 2023-11-06 11:20 UTC
Labels: enhancement
