### ISSUE TITLE
aws_athena_query_execution does not return all data

### ISSUE THREAD

**Issue by m-ronchi** [turbot/steampipe-plugin-aws#2345] opened 2024-11-26 15:28 UTC
**Describe the bug**
aws_athena_query_execution stops after some thousands of returned rows (we do ~3k queries per day, so we expect ~135k rows total)

**Steampipe version (`steampipe -v`)**
steampipe_export_aws v1.4.0

**Plugin version (`steampipe plugin list`)**
N/A

**To reproduce**
run `steampipe_export_aws aws_athena_query_execution --output jsonl` from inside a docker container
eventually export stops and produces these logs: 
```
[ERROR] 1732631381363: aws_athena_query_execution.getAwsAthenaQueryExecution: api_error="operation error Athena: GetQueryExecution, https response error StatusCode: 400, RequestID: , deserialization failed, failed to decode response body, invalid character '<' looking for beginning of value"
[ERROR] 1732631381363: callHydrate getAwsAthenaQueryExecution finished with error: operation error Athena: GetQueryExecution, https response error StatusCode: 400, RequestID: , deserialization failed, failed to decode response body, invalid character '<' looking for beginning of value
[ERROR] 1732631381363: aws_athena_query_execution.getAwsAthenaQueryExecution: api_error="operation error Athena: GetQueryExecution, https response error StatusCode: 400, RequestID: , deserialization failed, failed to decode response body, invalid character '<' looking for beginning of value"
[WARN]  1732631381363: hydrate error chan select: aws-1732631381363 (operation error Athena: GetQueryExecution, https response error StatusCode: 400, RequestID: , deserialization failed, failed to decode response body, invalid character '<' looking for beginning of value)
[ERROR] 1732631381363: table 'aws_athena_query_execution' failed to get column data: table 'aws_athena_query_execution' column 'query' requires hydrate data from getAwsAthenaQueryExecution, which failed with error operation error Athena: GetQueryExecution, https response error StatusCode: 400, RequestID: , deserialization failed, failed to decode response body, invalid character '<' looking for beginning of value.\n (aws-1732631381363)
[WARN]  1732631381363: getRow failed with error operation error Athena: GetQueryExecution, https response error StatusCode: 400, RequestID: , deserialization failed, failed to decode response body, invalid character '<' looking for beginning of value
[WARN]  1732631381363: QueryData StreamError table 'aws_athena_query_execution' column 'query' requires hydrate data from getAwsAthenaQueryExecution, which failed with error operation error Athena: GetQueryExecution, https response error StatusCode: 400, RequestID: , deserialization failed, failed to decode response body, invalid character '<' looking for beginning of value.\n (aws-1732631381363)
[WARN]  1732631381363: QueryData StreamError operation error Athena: GetQueryExecution, https response error StatusCode: 400, RequestID: , deserialization failed, failed to decode response body, invalid character '<' looking for beginning of value (aws-1732631381363)
[WARN]  1732631381363: streamRows execution has failed: aws-1732631381363 - calling queryCache.AbortSet (aws: table 'aws_athena_query_execution' column 'query' requires hydrate data from getAwsAthenaQueryExecution, which failed with error operation error Athena: GetQueryExecution, https response error StatusCode: 400, RequestID: , deserialization failed, failed to decode response body, invalid character '<' looking for beginning of value.\n)
[ERROR] 1732631381363: callHydrate getAwsAthenaQueryExecution finished with error: operation error Athena: GetQueryExecution, https response error StatusCode: 400, RequestID: , deserialization failed, failed to decode response body, invalid character '<' looking for beginning of value
[WARN]  1732631381363: queryData.streamRows returned error: aws: table 'aws_athena_query_execution' column 'query' requires hydrate data from getAwsAthenaQueryExecution, which failed with error operation error Athena: GetQueryExecution, https response error StatusCode: 400, RequestID: , deserialization failed, failed to decode response body, invalid character '<' looking for beginning of value.
[WARN]  1732631381363: hydrate error chan select: aws-1732631381363 (operation error Athena: GetQueryExecution, https response error StatusCode: 400, RequestID: , deserialization failed, failed to decode response body, invalid character '<' looking for beginning of value)
[ERROR] 1732631381363: table 'aws_athena_query_execution' failed to get column data: table 'aws_athena_query_execution' column 'total_execution_time_in_millis' requires hydrate data from getAwsAthenaQueryExecution, which failed with error operation error Athena: GetQueryExecution, https response error StatusCode: 400, RequestID: , deserialization failed, failed to decode response body, invalid character '<' looking for beginning of value.\n (aws-1732631381363)
[WARN]  1732631381363: getRow failed with error operation error Athena: GetQueryExecution, https response error StatusCode: 400, RequestID: , deserialization failed, failed to decode response body, invalid character '<' looking for beginning of value
[WARN]  1732631381363: QueryData StreamError table 'aws_athena_query_execution' column 'total_execution_time_in_millis' requires hydrate data from getAwsAthenaQueryExecution, which failed with error operation error Athena: GetQueryExecution, https response error StatusCode: 400, RequestID: , deserialization failed, failed to decode response body, invalid character '<' looking for beginning of value.\n (aws-1732631381363)
[WARN]  1732631381363: QueryData StreamError operation error Athena: GetQueryExecution, https response error StatusCode: 400, RequestID: , deserialization failed, failed to decode response body, invalid character '<' looking for beginning of value (aws-1732631381363)
[WARN]  1732631381363: executeForConnection aws returned error aws: table 'aws_athena_query_execution' column 'query' requires hydrate data from getAwsAthenaQueryExecution, which failed with error operation error Athena: GetQueryExecution, https response error StatusCode: 400, RequestID: , deserialization failed, failed to decode response body, invalid character '<' looking for beginning of value.\n, writing to CHAN
[WARN]  1732631381363: error channel received aws: table 'aws_athena_query_execution' column 'query' requires hydrate data from getAwsAthenaQueryExecution, which failed with error operation error Athena: GetQueryExecution, https response error StatusCode: 400, RequestID: , deserialization failed, failed to decode response body, invalid character '<' looking for beginning of value.
```
bin returns exit code 0

**Expected behavior**
all rows are exported. 
- if there is an error, the actual error response should be printed instead of failing to deserialize what appears to be xml instead of a json

**Additional context**
I containerized the steampipe_export_aws and run it on kubernetes

note: athena returns 400 in case of throttling, so you should detect and retry them ([ref](https://docs.aws.amazon.com/athena/latest/APIReference/CommonErrors.html))

**Comment by ParthaI** [comment] 2024-11-26 15:55
Hello @m-ronchi,

Sorry to hear that you're experiencing issues.

Could you please try running a query against the `aws_athena_query_execution` table using the Steampipe CLI in the same environment? This will help us determine whether the issue is related to the plugin code or the Steampipe export.

I also noticed that AWS throws a `ThrottlingException` with a 400 status code in some cases. If that's what's happening here, could you try adjusting the [max_error_retry_attempts](https://hub.steampipe.io/plugins/turbot/aws#configuration) and [min_error_retry_delay](https://hub.steampipe.io/plugins/turbot/aws#configuration) settings in your connection configuration to higher values? This might help mitigate the throttling issue.

Let us know how it goes, and we'll assist further if needed. Thank you!

**Comment by m-ronchi** [comment] 2024-11-26 17:21
Hi
I tried the steampipe cli and it returned `Error: aws: operation error Athena: ListQueryExecutions, exceeded maximum number of attempts, 9, https response error StatusCode: 400, RequestID: c1381f29-60bd-4b82-a8f7-f0fdda903308, api error ThrottlingException: Rate exceeded (SQLSTATE HV000)`

indeed I was throttled, limit is 5 req/s per account: [ref](https://docs.aws.amazon.com/athena/latest/ug/service-limits.html#service-limits-api-calls)

I will try with the options tomorrow

**Comment by ParthaI** [comment] 2024-11-27 04:23
Thank you so much, @m-ronchi, for your prompt response!

Additionally, you can also configure the [Global Rate Limiter](https://steampipe.io/docs/guides/limiter#concurrency--rate-limiting) to handle the `ThrottlingException` issue. Implementing the `BatchGetQueryExecution` feature might take some time as it requires a table design update. We truly appreciate your suggestion and will explore it to determine if it provides a viable solution.

Here’s an example of how you can configure the limiter in the AWS plugin's connection configuration file (`~/.steampipe/config/aws.spc`):

```hcl
plugin "aws" {
  limiter "athena_query_execution" {
    bucket_size  = 5
    fill_rate    = 5

    scope  = ["connection", "region", "service"]
    where  = "service = 'athena'"
  }
}
```

Alternatively:

```hcl
plugin "aws" {
  limiter "athena_query_execution_with_action" {
    bucket_size  = 5
    fill_rate    = 5

    scope  = ["connection", "region", "service", "action"]
    where  = "action = 'GetQueryExecutions' and service = 'athena'"
  }
}
```

Please adjust the limiter configuration parameters as needed, based on the behavior of the API. Let us know if you need further assistance, thank you! 🙏

**Comment by m-ronchi** [comment] 2024-11-27 10:07
Hi,
for now I set `AWS_MAX_ATTEMPTS=20` and it's working. if the problem reappears, I will add the config file.

I would like an option to make the exporter fail (i.e. exit code > 0) though, so I can be alerted if it happens again

**Comment by misraved** [comment] 2024-11-28 04:55
Thanks @m-ronchi for the confirmation 👍!!

We are closing this issue for now, if you have additional concerns or data points, please feel free to reopen the issue!!

Thanks once again for bringing up this issue.

**Closed by misraved** 2024-11-28 04:55 UTC
Labels: bug
