### ISSUE TITLE
`aws_vpc_eip` produce nil pointer error

### ISSUE THREAD

**Issue by project0** [turbot/steampipe-plugin-aws#2124] opened 2024-03-13 11:25 UTC
**Describe the bug**

Query `SELECT * FROM aws_vpc_eip` produces nil pointer errors

```
Error: aws_prod: rpc error: code = Internal desc = hydrate function listVpcEips failed with panic runtime error: invalid memory address or nil pointer dereference
```

**Steampipe version (`steampipe -v`)**
v0.22.0

**Plugin version (`steampipe plugin list`)**
hub.steampipe.io/plugins/turbot/aws@latest | 0.132.0

**To reproduce**

 `SELECT * FROM aws_vpc_eip`

**Expected behavior**

no error

**Additional context**
I spotted this when used together with the `aws_tags`  mod

**Comment by project0** [comment] 2024-03-13 11:30
same also happen with `listVpcVpnConnections`, probably related

**Comment by ParthaI** [comment] 2024-03-13 12:27
Hello @project0, my apologies for any inconvenience caused.

Upon querying the `aws_vpc_eip` and `aws_vpc_vpn_connection` tables, I didn't come across any errors within our setup. To further investigate this issue, I'd appreciate some additional information from you. Please have a look at the following requests:

- Could you please share your `aws.spc` file, ensuring any sensitive information is omitted?
- Does your `aws.spc` file include any regions that are not activated in your AWS Account?
- Would it be possible for you to provide the log details (set to INFO level) found in `~/.steampipe/logs/plugin-2024-03-*.log`? Here are the steps to retrieve the log details at the INFO level:
  - Set the environment variable with `export STEAMPIPE_LOG_LEVEL=INFO`
  - Execute `steampipe query`
  - Perform the query `select * from aws_vpc_eip`

Thank you!

**Comment by ParthaI** [comment] 2024-03-14 08:05
Thanks @project0, for the helpful insights,  It seems that adjusting the `regions` parameter in the `aws.spc` file might resolve the issue. Steampipe has yet to support getting the list of the enabled regions for an account. However, I've pushed a fix in the `add-nil-check-for-ec2-client` branch to address the panic error, specifically for the `aws_vpc_eip` and `aws_vpc_vpn_connection` tables. This should prevent the panic error from occurring with these tables.

It would be great if you would like to give it a try on the same branch.

I would greatly appreciate it if you could test this fix on the same branch.

Steps to give it a try in the branch `add-nil-check-for-ec2-client`:
1. Clone the repository with `git clone https://github.com/turbot/steampipe-plugin-aws.git`.
2. Change the directory with `cd steampipe-plugin-aws`.
3. Switch to the relevant branch with `git checkout add-nil-check-for-ec2-client`.
4. Compile the code with `make`.
5. Run the steampipe query

If you are still encountering any further issues, please let me know.

Thanks!

**Comment by project0** [comment] 2024-03-18 12:50
@ParthaI your fix does not seem to catch the caused nil pointer. 
Looking into the source, the function is not "aborted" and still tries to access the list. 
resp is nil in this case:
https://github.com/turbot/steampipe-plugin-aws/blob/main/aws/table_aws_vpc_eip.go#L187-L197

Adding a simple guard clause fix it: 
```
	if resp == nil {
		return nil, err
	}
```

**Comment by ParthaI** [comment] 2024-03-18 14:20
Thank you, @project0, for identifying the root cause of the error.

- Due to all regions being enabled in our environment, we were unable to replicate this error under the specified conditions. Additionally, we lack the authorization to implement AWS Service Control Policy in our environment, preventing a comprehensive test because it may affect other developers.
- If a service is not supported in a region, the API throws the same error when creating the client and attempting an API call with that client. The solution was incorporated in [this code segment](https://github.com/turbot/steampipe-plugin-aws/blob/main/aws/table_aws_amplify_app.go#L185-L188).
- My initial assumption proved to be wrong. While resource creation is possible in the mentioned region, the `Service Control Policy` prevents any action on this service in the specific region, according to the policy settings.
- I am not sure though, how other service operations would respond under a region-specific Service Control Policy.

Moving forward, we must explore the API with various services and consider a universal approach to address the nil pointer dereference issue in similar situations.

Your collaboration is greatly appreciated!

**Comment by project0** [comment] 2024-03-18 14:39
@ParthaI I think you misunderstood the difference between "supported service in region" and "Access prevented by SCP" as those are two completely different concepts. I am also even unsure if the client initiator even recognize not supported services in region. 

However, the SCP just adds a layer of permissive IAM permissions over a organization, when you initiate the client you will never see a error. SCPs only trigger when you try to access the respective api call for a resource. The same as with normal IAM policies.

In my case the region (and service) is enabled, but certain resources are denied by a SCP in this region. I think this is a pretty common setup to limit available resources in different regions and accounts.

**Comment by ParthaI** [comment] 2024-03-19 04:58
Thank you, this has clarified how to test the scenario.

**Comment by ParthaI** [comment] 2024-03-19 08:21
Hello, @project0, I've conducted tests on the tables after implementing the SCP at the organization level. We expect to encounter an access denied error, not an invalid memory address or nil pointer dereference error, when a Service Control Policy restricts an account in a specific region. My testing covered services such as EFS, RDS, EC2, S3, Cloudtrail, ECR, ECS, SFN, SSM, Route53, and WAF, and in all cases, we encountered the access denied error as expected.

Furthermore, I've submitted a [PR to address](https://github.com/turbot/steampipe-plugin-aws/pull/2136) issues with the `aws_vpc_eip` and `aws_vpc_vpn_connection` tables. With this fix, you should no longer experience any invalid memory address or nil pointer dereference errors.

Thank you for your support!

**Closed** 2024-03-20 10:06 UTC
Labels: bug
