### ISSUE TITLE
upgrade aws-sdk-go-v2/service/ssm to latest to gather  'ssm list-inventory-entries'

### ISSUE THREAD

**Issue by 7adityaraj** [turbot/steampipe-plugin-aws#1880] opened 2023-08-22 21:12 UTC
**Is your feature request related to a problem? Please describe.**

Currently, we are using ssm sdk version 1.35.1 ( https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/ssm@v1.35.1) whereas the latest is 1.37.2 (https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/ssm@v1.37.2)

We believe that the recent version will allow us to explore more details on inventory details like, 'InstanceDetailedInformation' is not present in 1.35.1 as it shows in response.

```
Error: operation error SSM: GetInventory, https response error StatusCode: 400, RequestID: ac7b65c2-c644-4191-82fd-7789e06669d2, InvalidResultAttributeException: Result type name AWS:InstanceDetailedInformation is not supported. Supported type names are: AWS:InstanceInformation, AWS:PatchSummary. Default result type name is AWS:InstanceInformation. (SQLSTATE HV000)
```

The aws cli cmds does provide with correct response.

```
aws ssm list-inventory-entries --instance-id i-00xyxxyzxyz --type-name AWS:InstanceDetailedInformation
--
{ 
  "TypeName": "AWS:InstanceDetailedInformation", "InstanceId": "i-0023112313cevwss", "SchemaVersion": "1.0", "CaptureTime": 
 "2023-08-22T15:01:28Z", "Entries": [ { "CPUCores": "1", "CPUHyperThreadEnabled": "true", "CPUModel": "Intel(R) Xeon(R) CPU 
 E5-2686 v4 @ 2.30GHz", "CPUSockets": "1", "CPUSpeedMHz": "2300", "CPUs": "2", "KernelVersion": "5.10.186- 179.751.amzn2.x86_64", "OSServicePack": "" } ] 
}
```

**Describe the solution you'd like**

Upgrade to ssm sdk version to latest

**Describe alternatives you've considered**

**Additional context**

turbobot community slack > https://turbot-community.slack.com/archives/C01UECB59A7/p1692732645439359

**Comment by ParthaI** [comment] 2023-08-29 05:13
@7adityaraj, Thank you for bringing up this issue. I delved into the problem further but unfortunately couldn't reproduce the issue. I have a couple of follow-up questions, could you kindly review them?

- What version of the AWS CLI are you using? (I couldn't find any Type name with `AWS:InstanceDetailedInformation` in the AWS CLI documentation: https://docs.aws.amazon.com/cli/latest/reference/ssm/list-inventory-entries.html)
- Would you be able to share the exact Steampipe query you are running?
- I noticed that in the inventory filter input, `AWS:InstanceDetailedInformation` cannot be used (Reference: https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/ssm@v1.37.2/types#InstanceInformation).
- I cross-verified this with the latest version of the [service package v1.37.5](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/ssm@v1.37.5).

I ran the AWS CLI command with version (aws-cli/2.13.0 Python/3.11.4 Darwin/22.3.0 source/arm64 prompt/off) got the following error

Command: `aws ec2 describe-instances --profile zero-intg-test --instance-id i-0cf3eb1f54441e384 --type-name AWS:InstanceDetailedInformation`
```

usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help

Unknown options: --type-name, AWS:InstanceDetailedInformation
```

With the [service package v1.37.5](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/ssm@v1.37.5) getting the following error. 

Query: `select * from aws_zero_intg_test.aws_ssm_inventory where type_name = 'AWS:InstanceDetailedInformation'`

```
Error: operation error SSM: GetInventory, https response error StatusCode: 400, RequestID: 56ef4608-1019-447d-9aea-5f08078b6d56, InvalidResultAttributeException: Result type name AWS:InstanceDetailedInformation is not supported. Supported type names are: AWS:InstanceInformation, AWS:PatchSummary. Default result type name is AWS:InstanceInformation. (SQLSTATE HV000)

+----+-----------+--------------+----------------+---------+--------+-------+-----------+--------+------------+------+
| id | type_name | capture_time | schema_version | content | schema | title | partition | region | account_id | _ctx |
+----+-----------+--------------+----------------+---------+--------+-------+-----------+--------+------------+------+
+----+-----------+--------------+----------------+---------+--------+-------+-----------+--------+------------+------+
```

Could you please provide more details? This will greatly assist us in further investigating the matter.

**Comment by cbruno10** [comment] 2023-09-15 17:41
Hi @7adityaraj , if you're still seeing this issue, please feel free to re-open this issue and if you could have a look at @ParthaI 's questions above, we can investigate more. Thanks!

**Comment by 7adityaraj** [comment] 2023-09-15 17:50
Hi @ParthaI @cbruno10 ,

Apologies for the delay.

About the steampipe cmd:
```
select
*
from
  aws_ssm_inventory as v,
  aws_ec2_instance as i,
  jsonb_array_elements(content) as c
where
  v.id = i.instance_id
  and v.type_name = 'AWS:InstanceDetailedInformation'
  and i.instance_state = 'running';
```


**however I ended up getting the following error -**

```Error: operation error SSM: GetInventory, https response error StatusCode: 400, RequestID: ac7b65c2-c644-4191-82fd-7789e06669d2, InvalidResultAttributeException: Result type name AWS:InstanceDetailedInformation is not supported. Supported type names are: AWS:InstanceInformation, AWS:PatchSummary. Default result type name is AWS:InstanceInformation. (SQLSTATE HV000)```

@ParthaI about the aws cli cmd, i have v2 installed but my cmd is aws ssm whereas you have been trying aws ec2

```
aws ssm list-inventory-entries --instance-id i-00xyxxyzxyz --type-name AWS:InstanceDetailedInformation
```

Hope this helps to trace the issue.

cc: @misraved

**Comment by bigdatasourav** [comment] 2023-11-06 13:19
Hey @7adityaraj, I have tried the above with the latest version - [ssm@v1.42.0](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/ssm@v1.42.0/types#ResultAttribute) but getting the same error-

```
select
*
from
  aws_ssm_inventory as v,
  aws_ec2_instance as i,
  jsonb_array_elements(content) as c
where
  v.id = i.instance_id
  and v.type_name = 'AWS:InstanceDetailedInformation'
  and i.instance_state = 'running';
  
 Error: operation error SSM: GetInventory, https response error StatusCode: 400, RequestID: e0554ba5-2479-4a3b-ab7d-4a0deebf88f5, InvalidResultAttributeException: Result type name AWS:InstanceDetailedInformation is not supported. Supported type names are: AWS:InstanceInformation, AWS:PatchSummary. Default result type name is AWS:InstanceInformation.
```
It looks like `InstanceDetailedInformation` is yet to be supported in the API.

We're closing this issue for now and will revisit it once API support becomes available. Please feel free to reopen the issue if you have any new information or contributions to share in the future.

**Closed** 2023-11-06 13:21 UTC
Labels: enhancement

**Comment by bigdatasourav** [comment] 2023-11-06 15:47
Raise an SDK [issue](https://github.com/aws/aws-sdk-go-v2/issues/2352) to track.
