### ISSUE TITLE
AWS plugin v0.107.0 hangs indefinately when querying aws_backup_* tables

### ISSUE THREAD

**Issue by captainfalcon23** [turbot/steampipe-plugin-aws#1796] opened 2023-06-26 01:59 UTC
**Describe the bug**
After upgrading aws plugin (and making no other changes) to v0.107.0, steampipe hangs forever when querying aws_backup_* tables.

**Steampipe version (`steampipe -v`)**
Steampipe v0.20.7

**Plugin version (`steampipe plugin list`)**
```
+---------------------------------------------------+---------+
| Installed Plugin                                  | Version |
+---------------------------------------------------+---------+
| hub.steampipe.io/plugins/turbot/aws@latest        | 0.107.0 |
| hub.steampipe.io/plugins/turbot/csv@latest        | 0.9.0   |
| hub.steampipe.io/plugins/turbot/steampipe@latest  | 0.8.0   |
+---------------------------------------------------+---------+
```

**To reproduce**
Happy to privately share the query I am using. 

**Expected behavior**
Plugin succeeds. Note that downgrading the plugin to 0.106.0, everything works fine.

**Additional context**
Job runs in gitlab pipeline, job running fine for a while, only caused by this one component update.

**Comment by misraved** [comment] 2023-06-26 05:20
Apologies for the inconvenience @captainfalcon23, we did update the Steampipe plugin SDK in `v0.107.0` plugin version which could be responsible for this behavior.

A couple of follow-up questions:
- Do other queries hang or is it just the `aws_backup_*` tables?
- Could you please share the plugin logs so we can pin down the error?
- Instead of a GitLab pipeline, could you please try out the query in your local system?
- Do other simple queries work for `aws_backup_*` tables? Like `select * from aws_backup_plan`?

**Comment by captainfalcon23** [comment] 2023-06-26 12:29
Heya @misraved,

Do other queries hang or is it just the aws_backup_* tables?
* Out of all my AWS jobs, only this one is exhibiting this issue

Could you please share the plugin logs so we can pin down the error?
* I will need to reproduce this and get the pipeline to echo out the logs. Will take a look at this tomorrow and get back to you

Instead of a GitLab pipeline, could you please try out the query in your local system?
* It seems to work fine in my local, noting in GItlab pipeline, it is using the instance profile to assume a role in each account

Do other simple queries work for aws_backup_* tables? Like select * from aws_backup_plan?
* These work fine on my local (noting my local has been around for a while/upgraded in place, whereas in pipeline, a new instance is created for every run)

**Comment by misraved** [comment] 2023-06-26 15:59
@captainfalcon23 apologies if it was unclear from the above message, but what version of AWS plugin are you using in your local?

**Comment by captainfalcon23** [comment] 2023-06-27 00:45
On my local I am running all the following plugins:
```
steampipe plugin list
+---------------------------------------------------+---------+
| Installed Plugin                                  | Version |
+---------------------------------------------------+---------+
| hub.steampipe.io/plugins/turbot/aws@latest        | 0.107.0 |
|                                                   |         |
| hub.steampipe.io/plugins/turbot/csv@latest        | 0.9.0   |
| hub.steampipe.io/plugins/turbot/jira@latest       | 0.10.1  |
| hub.steampipe.io/plugins/turbot/kubernetes@latest | 0.21.0  |
| hub.steampipe.io/plugins/turbot/steampipe@latest  | 0.8.0   |
+---------------------------------------------------+---------+
```

This is my full query which is run using `steampipe query <QUERY>; --output csv > outputfile.csv:

```
select
    a.region as "Region",
    a._ctx ->> 'connection_name' as "AWS accountid",
    a.resource_arn as "Protected_Resource_Backup_ARN",
    count(f.recovery_point_arn) as "Count_Total_AWSBackup_RecoveryPoints_for_resource",
    e.recovery_point_arn as "Recovery_Point_Latest_ARN",
    a.resource_type as "Protected_Resource_Backup_Type",
    a.last_backup_time as "Protected_Resource_Backup_Last_Backup_Time_Start",
    e.completion_date as "Recovery_Point_Backup_Completion_Date",
    DATE_PART('day', now() - e.completion_date) as "Calculated_Days_Since_Last_Backup",
    e.status as "Recovery_Point_Backup_Status",
    e.status_message as "Recovery_Point_Backup_Status_Message",
    e.lifecycle ->> 'DeleteAfterDays' as "Recovery_Point_Retention_Period_Days",
    e.calculated_lifecycle ->> 'DeleteAt' as "Recovery_Point_Deletion_Date",
    e.backup_vault_name as "Recovery_Point_Backup_Vault",
    a.region as "Protected_Resource_Backup_Region",
    b.title as "EBS_Vol_Name",
    b.volume_id as "EBS_Vol_ID",
    c.title as "RDS_Cluster_Name",
    d.title as "S3 Bucket Name"
from
    aws_all.aws_backup_protected_resource a
    left join aws_all.aws_ebs_volume b on a.resource_arn = b.arn
    and a.resource_type = 'EBS'
    left join aws_all.aws_rds_db_cluster c on a.resource_arn = c.arn
    and a.resource_type = 'Aurora'
    left join aws_all.aws_s3_bucket d on a.resource_arn = d.arn
    and a.resource_type = 'S3'
    left join aws_all.aws_backup_recovery_point e on e.account_id = a.account_id
    and a.resource_arn = e.resource_arn
    and (
        e.creation_date = a.last_backup_time
        or e.recovery_point_arn like '%continuous%'
    )
    left join aws_all.aws_backup_recovery_point f on e.account_id = a.account_id
    and a.resource_arn = f.resource_arn
group by
    a.region,
    a._ctx,
    a.resource_arn,
    e.recovery_point_arn,
    a.resource_type,
    a.last_backup_time,
    e.completion_date,
    e.status,
    e.status_message,
    e.lifecycle,
    e.calculated_lifecycle,
    e.backup_vault_name,
    b.title,
    b.volume_id,
    c.title,
    d.title
order by
    a._ctx,
    a.resource_type,
    e.recovery_point_arn,
    b.title,
    c.title desc,
    d.title desc; --output csv
```

The entire query seems to hang in my local as well, but there are no useful logs. :( 

I have reproduced this in gitlab now, here are the plugin logs:
```
[root@runner-xzsqqkpb-project-352-concurrent-0 logs]# cat plugin-2023-06-27.log
2023-06-27 00:27:39.679 UTC [ERROR] steampipe-plugin-csv.plugin: [ERROR] csv.tableCSV: header_parse_error=EOF path=/builds/ops/reporting/reporting/aws-get-latest-backups-status/aws-get-latest-backups-status.csv header=[]
2023-06-27 00:27:39.680 UTC [ERROR] steampipe-plugin-csv.plugin: [ERROR] csv.PluginTables: create_table_error="failed to parse file header /builds/ops/reporting/reporting/aws-get-latest-backups-status/aws-get-latest-backups-status.csv: EOF" path=/builds/ops/reporting/reporting/aws-get-latest-backups-status/aws-get-latest-backups-status.csv
2023-06-27 00:27:39.680 UTC [WARN]  failed to set connection config for csv: failed to parse file header /builds/ops/reporting/reporting/aws-get-latest-backups-status/aws-get-latest-backups-status.csv: EOF
[root@runner-xzsqqkpb-project-352-concurrent-0 logs]#
```

And these are the database logs:
```
[root@runner-xzsqqkpb-project-352-concurrent-0 logs]# cat database-2023-06-27.log |grep -v "COMMENT ON "
2023-06-27 00:27:38.036 UTC [231] LOG:  starting PostgreSQL 14.2 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 4.8.4-2ubuntu1~14.04.4) 4.8.4, 64-bit
2023-06-27 00:27:38.037 UTC [231] LOG:  listening on IPv4 address "127.0.0.1", port 9193
2023-06-27 00:27:38.037 UTC [231] LOG:  could not bind IPv6 address "::1": Cannot assign requested address
2023-06-27 00:27:38.041 UTC [231] LOG:  listening on Unix socket "/tmp/.s.PGSQL.9193"
2023-06-27 00:27:38.050 UTC [233] LOG:  database system was shut down at 2023-06-27 00:27:37 UTC
2023-06-27 00:27:38.061 UTC [231] LOG:  database system is ready to accept connections
2023-06-27 00:27:38.184 UTC [240] LOG:  connection received: host=127.0.0.1 port=58562
2023-06-27 00:27:38.189 UTC [240] LOG:  connection authorized: user=root database=postgres
2023-06-27 00:27:38.212 UTC [240] LOG:  disconnection: session time: 0:00:00.028 user=root database=postgres host=127.0.0.1 port=58562
2023-06-27 00:27:38.220 UTC [241] LOG:  connection received: host=127.0.0.1 port=58564
2023-06-27 00:27:38.233 UTC [241] LOG:  connection authorized: user=root database=postgres application_name=steampipe_8c18 SSL enabled (protocol=TLSv1.2, cipher=ECDHE-RSA-AES256-GCM-SHA384, bits=256)
2023-06-27 00:27:38.249 UTC [241] LOG:  disconnection: session time: 0:00:00.028 user=root database=postgres host=127.0.0.1 port=58564
2023-06-27 00:27:38.251 UTC [242] LOG:  connection received: host=127.0.0.1 port=58566
2023-06-27 00:27:38.254 UTC [242] LOG:  connection authorized: user=root database=steampipe application_name=steampipe_8c18 SSL enabled (protocol=TLSv1.2, cipher=ECDHE-RSA-AES256-GCM-SHA384, bits=256)
2023-06-27 00:27:38.358 UTC [242] LOG:  disconnection: session time: 0:00:00.107 user=root database=steampipe host=127.0.0.1 port=58566
2023-06-27 00:27:38.397 UTC [260] LOG:  connection received: host=127.0.0.1 port=58568
2023-06-27 00:27:38.406 UTC [260] LOG:  connection authorized: user=root database=steampipe application_name=steampipe_8c18 SSL enabled (protocol=TLSv1.2, cipher=ECDHE-RSA-AES256-GCM-SHA384, bits=256)
2023-06-27 00:27:38.481 UTC [269] LOG:  connection received: host=127.0.0.1 port=58570
2023-06-27 00:27:38.485 UTC [269] LOG:  connection authorized: user=root database=steampipe application_name=steampipe_8c18 SSL enabled (protocol=TLSv1.2, cipher=ECDHE-RSA-AES256-GCM-SHA384, bits=256)
2023-06-27 00:27:38.493 UTC [270] LOG:  connection received: host=127.0.0.1 port=58572
2023-06-27 00:27:38.496 UTC [270] LOG:  connection authorized: user=root database=steampipe application_name=steampipe_8c18 SSL enabled (protocol=TLSv1.2, cipher=ECDHE-RSA-AES256-GCM-SHA384, bits=256)
2023-06-27 00:27:38.505 UTC [260] LOG:  disconnection: session time: 0:00:00.108 user=root database=steampipe host=127.0.0.1 port=58568
2023-06-27 00:27:38.507 UTC [272] LOG:  connection received: host=127.0.0.1 port=58574
2023-06-27 00:27:38.508 UTC [273] LOG:  connection received: host=127.0.0.1 port=58576
2023-06-27 00:27:38.512 UTC [272] LOG:  connection authorized: user=steampipe database=steampipe application_name=steampipe_8c18 SSL enabled (protocol=TLSv1.2, cipher=ECDHE-RSA-AES256-GCM-SHA384, bits=256)
2023-06-27 00:27:38.515 UTC [273] LOG:  connection authorized: user=root database=steampipe application_name=pm_steampipe_96d4 SSL enabled (protocol=TLSv1.2, cipher=ECDHE-RSA-AES256-GCM-SHA384, bits=256)
2023-06-27 00:27:38.535 UTC [272] ERROR:  relation "aws_all.aws_backup_protected_resource" does not exist at character 1261
2023-06-27 00:27:38.535 UTC [272] STATEMENT:  select
                    a.region as "Region",
                    a._ctx ->> 'connection_name' as "AWS accountid",
                    a.resource_arn as "Protected_Resource_Backup_ARN",
                                count(f.recovery_point_arn) as "Count_Total_AWSBackup_RecoveryPoints_for_resource",
                    e.recovery_point_arn as "Recovery_Point_Latest_ARN",
                    a.resource_type as "Protected_Resource_Backup_Type",
                    a.last_backup_time as "Protected_Resource_Backup_Last_Backup_Time_Start",
                    e.completion_date as "Recovery_Point_Backup_Completion_Date",
                    DATE_PART('day', now() - e.completion_date) as "Calculated_Days_Since_Last_Backup",
                    e.status as "Recovery_Point_Backup_Status",
                    e.status_message as "Recovery_Point_Backup_Status_Message",
                    e.lifecycle ->> 'DeleteAfterDays' as "Recovery_Point_Retention_Period_Days",
                    e.calculated_lifecycle ->> 'DeleteAt' as "Recovery_Point_Deletion_Date",
                    e.backup_vault_name as "Recovery_Point_Backup_Vault",
                    a.region as "Protected_Resource_Backup_Region",
                    b.title as "EBS_Vol_Name",
                    b.volume_id as "EBS_Vol_ID",
                    c.title as "RDS_Cluster_Name",
                    d.title as "S3 Bucket Name"

                    from

                    aws_all.aws_backup_protected_resource a
                    left join aws_all.aws_ebs_volume b on a.resource_arn = b.arn
                    and a.resource_type = 'EBS'
                    left join aws_all.aws_rds_db_cluster c on a.resource_arn = c.arn
                    and a.resource_type = 'Aurora'
                    left join aws_all.aws_s3_bucket d on a.resource_arn = d.arn
                    and a.resource_type = 'S3'
                    left join aws_all.aws_backup_recovery_point e on e.account_id = a.account_id
                    and a.resource_arn = e.resource_arn
                    and (e.creation_date = a.last_backup_time or e.recovery_point_arn like '%continuous%')
                                left join aws_all.aws_backup_recovery_point f on e.account_id = a.account_id
                    and a.resource_arn = f.resource_arn

                                group by a.region, a._ctx,  a.resource_arn, e.recovery_point_arn, a.resource_type, a.last_backup_time, e.completion_date, e.status, e.status_message, e.lifecycle, e.calculated_lifecycle,  e.backup_vault_name, b.title, b.volume_id, c.title, d.title

                    order by
                    a._ctx,
                    a.resource_type,
                    e.recovery_point_arn,
                    b.title,
                    c.title desc,
                    d.title desc;
2023-06-27 00:27:40.462 UTC [316] LOG:  connection received: host=127.0.0.1 port=58586
2023-06-27 00:27:40.479 UTC [316] LOG:  connection authorized: user=root database=steampipe application_name=pm_steampipe_96d4 SSL enabled (protocol=TLSv1.2, cipher=ECDHE-RSA-AES256-GCM-SHA384, bits=256)
2023-06-27 00:27:52.143 UTC [316] LOG:  could not receive data from client: Connection reset by peer
2023-06-27 00:27:52.143 UTC [316] LOG:  disconnection: session time: 0:00:11.681 user=root database=steampipe host=127.0.0.1 port=58586
2023-06-27 00:27:52.228 UTC [318] LOG:  connection received: host=127.0.0.1 port=32976
2023-06-27 00:27:52.255 UTC [320] LOG:  connection received: host=127.0.0.1 port=32980
2023-06-27 00:27:52.255 UTC [319] LOG:  connection received: host=127.0.0.1 port=32978
2023-06-27 00:27:52.256 UTC [318] LOG:  connection authorized: user=root database=steampipe application_name=pm_steampipe_96d4 SSL enabled (protocol=TLSv1.2, cipher=ECDHE-RSA-AES256-GCM-SHA384, bits=256)
2023-06-27 00:27:52.258 UTC [321] LOG:  connection received: host=127.0.0.1 port=32982
2023-06-27 00:27:52.268 UTC [322] LOG:  connection received: host=127.0.0.1 port=32984
2023-06-27 00:27:52.298 UTC [322] LOG:  connection authorized: user=root database=steampipe application_name=pm_steampipe_96d4 SSL enabled (protocol=TLSv1.2, cipher=ECDHE-RSA-AES256-GCM-SHA384, bits=256)
2023-06-27 00:27:52.298 UTC [321] LOG:  connection authorized: user=root database=steampipe application_name=pm_steampipe_96d4 SSL enabled (protocol=TLSv1.2, cipher=ECDHE-RSA-AES256-GCM-SHA384, bits=256)
2023-06-27 00:27:52.311 UTC [323] LOG:  connection received: host=127.0.0.1 port=32986
2023-06-27 00:27:52.344 UTC [324] LOG:  connection received: host=127.0.0.1 port=32988
2023-06-27 00:27:52.350 UTC [326] LOG:  connection received: host=127.0.0.1 port=32992
2023-06-27 00:27:52.350 UTC [325] LOG:  connection received: host=127.0.0.1 port=32990
2023-06-27 00:27:52.356 UTC [326] LOG:  connection authorized: user=root database=steampipe application_name=pm_steampipe_96d4 SSL enabled (protocol=TLSv1.2, cipher=ECDHE-RSA-AES256-GCM-SHA384, bits=256)
2023-06-27 00:27:52.363 UTC [323] LOG:  connection authorized: user=root database=steampipe application_name=pm_steampipe_96d4 SSL enabled (protocol=TLSv1.2, cipher=ECDHE-RSA-AES256-GCM-SHA384, bits=256)
2023-06-27 00:27:52.366 UTC [324] LOG:  connection authorized: user=root database=steampipe application_name=pm_steampipe_96d4 SSL enabled (protocol=TLSv1.2, cipher=ECDHE-RSA-AES256-GCM-SHA384, bits=256)
2023-06-27 00:27:52.383 UTC [319] LOG:  connection authorized: user=root database=steampipe application_name=pm_steampipe_96d4 SSL enabled (protocol=TLSv1.2, cipher=ECDHE-RSA-AES256-GCM-SHA384, bits=256)
2023-06-27 00:27:52.392 UTC [320] LOG:  connection authorized: user=root database=steampipe application_name=pm_steampipe_96d4 SSL enabled (protocol=TLSv1.2, cipher=ECDHE-RSA-AES256-GCM-SHA384, bits=256)
2023-06-27 00:27:52.402 UTC [325] LOG:  connection authorized: user=root database=steampipe application_name=pm_steampipe_96d4 SSL enabled (protocol=TLSv1.2, cipher=ECDHE-RSA-AES256-GCM-SHA384, bits=256)
2023-06-27 00:27:52.415 UTC [327] LOG:  connection received: host=127.0.0.1 port=32994
2023-06-27 00:27:52.449 UTC [328] LOG:  connection received: host=127.0.0.1 port=32996
2023-06-27 00:27:52.482 UTC [330] LOG:  connection received: host=127.0.0.1 port=33000
2023-06-27 00:27:52.483 UTC [329] LOG:  connection received: host=127.0.0.1 port=32998
2023-06-27 00:27:52.499 UTC [327] LOG:  connection authorized: user=root database=steampipe application_name=pm_steampipe_96d4 SSL enabled (protocol=TLSv1.2, cipher=ECDHE-RSA-AES256-GCM-SHA384, bits=256)
2023-06-27 00:27:52.507 UTC [329] LOG:  connection authorized: user=root database=steampipe application_name=pm_steampipe_96d4 SSL enabled (protocol=TLSv1.2, cipher=ECDHE-RSA-AES256-GCM-SHA384, bits=256)
2023-06-27 00:27:52.509 UTC [331] LOG:  connection received: host=127.0.0.1 port=33002
2023-06-27 00:27:52.513 UTC [330] LOG:  connection authorized: user=root database=steampipe application_name=pm_steampipe_96d4 SSL enabled (protocol=TLSv1.2, cipher=ECDHE-RSA-AES256-GCM-SHA384, bits=256)
2023-06-27 00:27:52.515 UTC [328] LOG:  connection authorized: user=root database=steampipe application_name=pm_steampipe_96d4 SSL enabled (protocol=TLSv1.2, cipher=ECDHE-RSA-AES256-GCM-SHA384, bits=256)
2023-06-27 00:27:52.520 UTC [333] LOG:  connection received: host=127.0.0.1 port=33006
2023-06-27 00:27:52.533 UTC [331] LOG:  connection authorized: user=root database=steampipe application_name=pm_steampipe_96d4 SSL enabled (protocol=TLSv1.2, cipher=ECDHE-RSA-AES256-GCM-SHA384, bits=256)
2023-06-27 00:27:52.537 UTC [333] LOG:  connection authorized: user=root database=steampipe application_name=pm_steampipe_96d4 SSL enabled (protocol=TLSv1.2, cipher=ECDHE-RSA-AES256-GCM-SHA384, bits=256)
2023-06-27 00:27:52.539 UTC [332] LOG:  connection received: host=127.0.0.1 port=33004
2023-06-27 00:27:52.545 UTC [334] LOG:  connection received: host=127.0.0.1 port=33008
2023-06-27 00:27:52.551 UTC [332] LOG:  connection authorized: user=root database=steampipe application_name=pm_steampipe_96d4 SSL enabled (protocol=TLSv1.2, cipher=ECDHE-RSA-AES256-GCM-SHA384, bits=256)
2023-06-27 00:27:52.580 UTC [334] LOG:  connection authorized: user=root database=steampipe application_name=pm_steampipe_96d4 SSL enabled (protocol=TLSv1.2, cipher=ECDHE-RSA-AES256-GCM-SHA384, bits=256)


















2023-06-27 00:27:59.434 UTC [318] LOG:  disconnection: session time: 0:00:07.206 user=root database=steampipe host=127.0.0.1 port=32976
2023-06-27 00:27:59.434 UTC [328] LOG:  disconnection: session time: 0:00:06.985 user=root database=steampipe host=127.0.0.1 port=32996
2023-06-27 00:27:59.434 UTC [322] LOG:  disconnection: session time: 0:00:07.166 user=root database=steampipe host=127.0.0.1 port=32984
2023-06-27 00:27:59.434 UTC [334] LOG:  disconnection: session time: 0:00:06.889 user=root database=steampipe host=127.0.0.1 port=33008
2023-06-27 00:27:59.434 UTC [325] LOG:  disconnection: session time: 0:00:07.084 user=root database=steampipe host=127.0.0.1 port=32990
2023-06-27 00:27:59.437 UTC [333] LOG:  disconnection: session time: 0:00:06.917 user=root database=steampipe host=127.0.0.1 port=33006
2023-06-27 00:27:59.437 UTC [332] LOG:  disconnection: session time: 0:00:06.898 user=root database=steampipe host=127.0.0.1 port=33004
2023-06-27 00:27:59.437 UTC [273] LOG:  disconnection: session time: 0:00:20.928 user=root database=steampipe host=127.0.0.1 port=58576
2023-06-27 00:27:59.437 UTC [330] LOG:  disconnection: session time: 0:00:06.955 user=root database=steampipe host=127.0.0.1 port=33000
2023-06-27 00:27:59.439 UTC [329] LOG:  disconnection: session time: 0:00:06.955 user=root database=steampipe host=127.0.0.1 port=32998
2023-06-27 00:27:59.439 UTC [326] LOG:  disconnection: session time: 0:00:07.089 user=root database=steampipe host=127.0.0.1 port=32992
2023-06-27 00:27:59.440 UTC [320] LOG:  disconnection: session time: 0:00:07.185 user=root database=steampipe host=127.0.0.1 port=32980
2023-06-27 00:27:59.441 UTC [319] LOG:  disconnection: session time: 0:00:07.186 user=root database=steampipe host=127.0.0.1 port=32978
2023-06-27 00:27:59.441 UTC [327] LOG:  disconnection: session time: 0:00:07.026 user=root database=steampipe host=127.0.0.1 port=32994
2023-06-27 00:27:59.443 UTC [331] LOG:  disconnection: session time: 0:00:06.933 user=root database=steampipe host=127.0.0.1 port=33002
2023-06-27 00:27:59.443 UTC [323] LOG:  disconnection: session time: 0:00:07.132 user=root database=steampipe host=127.0.0.1 port=32986
2023-06-27 00:27:59.444 UTC [321] LOG:  disconnection: session time: 0:00:07.186 user=root database=steampipe host=127.0.0.1 port=32982
2023-06-27 00:27:59.446 UTC [324] LOG:  disconnection: session time: 0:00:07.102 user=root database=steampipe host=127.0.0.1 port=32988
2023-06-27 00:29:38.266 UTC [270] LOG:  could not receive data from client: Connection reset by peer
2023-06-27 00:29:38.266 UTC [269] LOG:  could not receive data from client: Connection reset by peer
2023-06-27 00:29:38.266 UTC [270] LOG:  disconnection: session time: 0:01:59.773 user=root database=steampipe host=127.0.0.1 port=58572
2023-06-27 00:29:38.266 UTC [269] LOG:  disconnection: session time: 0:01:59.785 user=root database=steampipe host=127.0.0.1 port=58570
```

Gathered these logs while job was running:
![image](https://github.com/turbot/steampipe-plugin-aws/assets/66669505/e6337c36-15fc-4056-b549-02f1a0b8337b)

Noting also that this job usually completes in under 2min 30s:
![image](https://github.com/turbot/steampipe-plugin-aws/assets/66669505/607afcfd-5408-4537-a92b-70299038dcc4)

**Comment by misraved** [comment] 2023-06-28 12:32
Thank you so much @captainfalcon23 for such detailed logs. I tried to reproduce the error locally without much success.

From the logs, it is not very clear what could have triggered the error.

A couple of suggestions to try out:
- Could you try running the query independently on a terminal without passing in the output format argument?
- Probably I missed this before, but how many accounts are you trying to query and what number of resources are we expecting as a part of the query output?

**Comment by captainfalcon23** [comment] 2023-06-28 23:33
No probs @misraved 

I have run it in my local using the following methods:
* steampipe interactive client -> just hangs
* by passing the query to "steampipe query" WITHOUT --output csv -> just hangs... in fact, I can't even CTRL+C to kill it ... ? I had to kill the pid
* by passing the query to "steampipe query" WITH --output csv -> no attempt
* by passing the query to "steampipe query" WITH --output csv AND sending the output to blah.csv -> no attempt

I have the following installed:
```
+---------------------------------------------------+---------+
| Installed Plugin                                  | Version |
+---------------------------------------------------+---------+
| hub.steampipe.io/plugins/turbot/aws@latest        | 0.107.0 |
|                                                   |         |
| hub.steampipe.io/plugins/turbot/csv@latest        | 0.9.0   |
| hub.steampipe.io/plugins/turbot/jira@latest       | 0.10.1  |
| hub.steampipe.io/plugins/turbot/kubernetes@latest | 0.21.0  |
| hub.steampipe.io/plugins/turbot/steampipe@latest  | 0.8.0   |
+---------------------------------------------------+---------+
```
Total # of accounts (via an aggregation) is 19. I expect around 260 records in the final output.

I previously said it worked fine in my local, which is interesting as today it did not, perhaps I didn't run the full query and only was testing select statements on the individual tables.

Plugin log is empty, so reproduced with DEBUG and attached the logs. [logs.zip](https://github.com/turbot/steampipe-plugin-aws/files/11900656/logs.zip)


(PS. when DEBUG is enabled, everything just gets reported at INFO level, let me know if thats expected or not, and if no, I will raise a separate issue in the main steampipe project)

**Comment by misraved** [comment] 2023-06-30 05:46
Thank you so much @captainfalcon23 for the details.

I believe this is an SDK issue that could be responsible for the hang.

Adding the issue reference here for tracking - https://github.com/turbot/steampipe-plugin-sdk/issues/583

Once again, thanks for providing the detailed level logs. It has definitely eased out the debugging process.

**Comment by misraved** [comment] 2023-07-03 18:18
Hi @captainfalcon23, thanks for being patient with us 👍. 

As we continue to debug and fix the above issue at the SDK level, we would love it if you could provide us with some valuable feedback on the `v5.6.0-alpha.2` SDK version.

I have created a PR with the new SDK version - https://github.com/turbot/steampipe-plugin-aws/pull/1810

Could you please build the above branch and let us know if it fixes this issue?

Steps to use the branch:
- Clone the repository - `git clone https://github.com/turbot/steampipe-plugin-aws.git`
- Switch to the branch - `git switch update-sdk-v560-alpha-2`
- Run make - `make`
- Test the failing queries

Since you have a good testing environment, it would be great if you could help us and provide some additional feedback on the new SDK version as we continue to run other queries and compliance mods to weed out the error 👍.

**Comment by captainfalcon23** [comment] 2023-07-03 23:08
Hi @misraved 

Tested this morning using that branch and same issue, just hangs forever. Pls ping me on slack (captainfalcon23) and I'll be happy to share my query also :)

**Comment by misraved** [comment] 2023-07-04 19:29
Apologies for that @captainfalcon23, we are still looking to fix this issue in the SDK layer. Hopefully should have a fix in the new SDK version 👍.

**Comment by graza-io** [comment] 2023-09-21 09:57
Just leaving a note as I attempted to reproduce this error locally but wasn't able to do so.

I pulled the logs from the zip file and saw nothing helpful there, only issues are seemingly after the request was terminated.

Looking at the `local` logs you posted above, I did notice that there was an error:
```
2023-06-27 00:27:38.535 UTC [272] ERROR:  relation "aws_all.aws_backup_protected_resource" does not exist at character 1261
```

Which I was able to replicate since my aggregator is `_all_aws` not `aws_all` I received:
```
[5026] ERROR:  relation "aws_all.aws_backup_protected_resource" does not exist at character 1056
```
(The character diff is due to me tidying up the spaces, etc in the query - one I updated the aggregator to use mine, the query ran successfully.

Would you be able to retest locally using latest Steampipe (v0.20.12) & AWS plugin (0.118.1) versions ensuring you have the correct `aws_all` aggregator configured?

`steampipe query "select * from aws_all.aws_backup_protected_resource limit 1;"`

If the above returns successfully, please extract the `sql` file from the attached `zip` into the working directory:
[issue_1796.sql.zip](https://github.com/turbot/steampipe-plugin-aws/files/12683092/issue_1796.sql.zip)

Please test with:
```shell
STEAMPIPE_LOG_LEVEL=debug steampipe query issue_1796.sql --output=csv
```

Hopefully this should work, please let us know and if not, please include log files.

**Comment by captainfalcon23** [comment] 2023-09-24 05:04
Hi @graza-io ,

`Would you be able to retest locally using latest Steampipe (v0.20.12) & AWS plugin (0.118.1) versions ensuring you have the correct aws_all aggregator configured?`
Yes, did this today with the latest of both and specifically using the query you provided, and it just hangs indefinitely.  I also tried downgrading the AWS plugin back to 0.106.0 and the query worked and got the results within 30sec.

I have attached the logs from the failures and the success, ignore the error "ERROR:  aggregator 'aws_all' with pattern 'aws_*' matches no connections" this is because I hadn't updated my config file with the older AWS plugin.

Note also, it is impossible to kill the hung steampipe using CTRL + C, it seems I need to use `pkill steampipe` and `pkill postgres` to actually kill it. 

[logs.zip](https://github.com/turbot/steampipe-plugin-aws/files/12707830/logs.zip)

**Comment by graza-io** [comment] 2023-09-25 07:49
Ah thanks, looks like the change to SDK v5.5.0 (whilst generally giving improvements) is causing an issue in this circumstance.

I know work is almost complete on SDK v5.6.0 which will contain a fix for cache deadlock (which _may_ be the issue here), unfortunately I can't give you a better ETA than `soon`.

If you wish to test the prerelease of this change I think you can obtain a copy of the code and update the relevant reference in `go.mod`

So `github.com/turbot/steampipe-plugin-sdk/v5 v5.5.0` => `github.com/turbot/steampipe-plugin-sdk/v5 v5.6.0-rc.30` (you will need to update the deps using your usual go tooling) then ensuring no active Steampipe sessions exist run `make` which should override your `latest` with the build output.

**Comment by captainfalcon23** [comment] 2023-09-25 08:07
Thanks @graza-io lets leave the ticket open till it is released along with relevant aws plugin and then we can retest.

**Comment by graza-io** [comment] 2023-09-25 09:26
Actually, if you have the time - was hoping you would test against the aforementioned RC.

If you don't have the time I understand, would just be useful to have a reliable test case.

**Comment by captainfalcon23** [comment] 2023-09-26 23:57
Hey @graza-io ,

Okay, have recompiled with the new SDK and.... it works fine now!!

Timing for the full query:
```
time STEAMPIPE_LOG_LEVEL=debug steampipe query issue.sql --output=csv
real    0m21.612s
user    0m11.247s
sys     0m2.595s
```

Glad we could get to the bottom of it finally (and so strange that this issue only occurred with this particular query). Do you have any insights to the "cache deadlock" you mentioned?

I think this can either be closed, or put on hold with new AWS plugin is released.

**Comment by misraved** [comment] 2023-09-27 06:19
Thanks @graza-io for the input 👍, @captainfalcon23 glad to see that the issue has been resolved 😃 and thank you so much for taking out time to test the latest plugin build 👍.

We will be releasing a new AWS plugin with the latest SDK shortly, so I believe it is good to close the issue.

Please feel free to reopen the issue if you have more questions 👍.

**Closed by misraved** 2023-09-27 06:19 UTC
Labels: bug
